# **Quality check segmentations**

***Prior to this notebook, you should have completed the organelle and masks segmentations using notebooks 1.0-1.8, the batch_processing_segmentations wporkflow, or the `infer-subc` plugin for Napari, called `organelle-segmenter-plugin`.***

### **Purpose**
1. **Optional**: Visual inspection the segmentation outputs for each image in your dataset (***optional***)

    *We <ins>highly recommend</ins> going through this process. It is especially important for datasets where errors in the segmentations can have large impacts on the downstream statistical outcomes (e.g., datasets that do NOT have 100's of images per condition for example).*
2. **Recommended**: Applyication of automated quality checks to ensure the data is prepared for analysis in `Part 2 - Quantification`.
3. **REQUIRED**: Separation of the `masks`/`soma_neurites` files into separate `cell`, `nuc`, `soma`, and `neurites` segmentation files.

    *This is required for downstream analysis in `infer-subc` `Part 2`. For some background, this step is required due to technical limitations of the Napari plugin; each workflow can only output one file, but the segmentations of the `cell` and `nucleus` or `soma` and `neurites` are derived from the same workflows.*

### ➡️ **Input**
**The following files will be used as input in this notebook:**
1. "Raw" confocal microscopy image (".tiff", ".tif", or ".czi") where each channel of the image represents one of the organelles being segmented
2. The segmentation files created in `infer-subc` Notebooks or Napari plugin or derived from alternative segmentation tools.

**You will also need the following:**
1. An empty folder to save segmentation files after editing
2. An empty folder to save the FINAL segmentation dataset (i.e., combining edited files with original segmentation files that did not need editing)

### **Output** ➡️
**The output from this notebook will include:**
1. A folder containing any edited mask files saved as ".tiff"
2. A folder containing ALL FINAL segmentation files that are ready for quantification

-----

### 👣 **Summary of steps**  

➡️ **QUALITY CHECK SEGMENTATIONS**
- **`Step 1`** - Define the paths to your data and final output locations

- **`Step 2`** - Import and visualize segmentations

- **`Step 3`** - Edit individual segmentations (***optional***) 

- **`Step 4`** - Automated quality checks for segmentations before quantification (***recommended***)

- **`Step 5`** - Save organelle and region segmentations into specified folder

    - This step will also save the `cell` and `nuclei` as well as `soma` and `neurites` segmentations as separate files (***required***)

---------------------
## **IMPORTS**

#### &#x1F3C3; **Run code; no user input required**

&#x1F453; **FYI:** This code block imports the Python packages needed in the QC steps below.

In [1]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
import os
from pathlib import Path
import pandas as pd

import napari
from napari.utils.colormaps import Colormap
from napari.settings import get_settings
settings = get_settings()
settings.application.ipy_interactive = True

viewer = napari.Viewer()

import colorsys
from infer_subc.core.file_io import (read_czi_image,
                                        export_inferred_organelle,
                                        import_inferred_organelle,
                                        list_image_files,
                                        sample_input_QC)
from infer_subc.utils.batch import filter_segmentation, edit_segmentation

%load_ext autoreload
%autoreload 2

WARNING: QWindowsWindow::setGeometry: Unable to set geometry 1086x657+3235-838 (frame: 1102x696+3227-869) on QWidgetWindow/"_QtMainWindowClassWindow" on "\\.\DISPLAY3". Resulting geometry: 723x658+3232-852 (frame: 739x697+3224-883) margins: 8, 31, 8, 8 minimum size: 385x495 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=401,534 maxtrack=0,0)
05-May-26 13:08:09 - vispy    - WARNING  - QWindowsWindow::setGeometry: Unable to set geometry 1086x657+3235-838 (frame: 1102x696+3227-869) on QWidgetWindow/"_QtMainWindowClassWindow" on "\\.\DISPLAY3". Resulting geometry: 723x658+3232-852 (frame: 739x697+3224-883) margins: 8, 31, 8, 8 minimum size: 385x495 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=401,534 maxtrack=0,0)

-----

## **QUALITY CHECK OF SEGMENTATIONS**

**NOTE: DO NOT EDIT ANY OF THE LAYER NAMES IN NAPARI**

These layer names are used throughout the notebook to find the segmentations and collect them to ensure any edits you have made to the segmentations are saved. Additionally, these names are used to signify the unedited segmentations as well. Editing these names will break the program as your segmentations will no longer be found by the code.

### **`STEP 1` - Define the paths to your data**

#### &#x1F6D1; &#x270D; **User Input Required:**

&#x1F453; **FYI:** *This code block utilizes a new method of loading in images that is similar to that which is found in [`2.0_quantification_setup`](..\part_2_quantification\2.0_quantification_setup.ipynb). This method utilizes variable lists which you may the suffixes, and raw image channels. The orders of these lists are matched throughout. Additionally, a dictionary is provided for multichannel image segmentations (think the mask segmentation which contains both the nucleus and cell masks). This dictionary uses a value matching to the suffix of their segmentation file and assigns it to a list of new suffixes that matches the number of channels in the multichannel image.

Please specify if you will be using the Sample Data or not.
- `sample_data_type`: Specify which sample data type you wish to use by typing "pri-neuron", "pri-astrocyte", "iNeuron" or "iPSC". Indicate `None` if you do not wish to use the sample data. If using sample data, you must have followed the sample data setup found in the [sample-data_setup.ipynb](/infer-subc/sample_data/sample-data_setup.ipynb) file.

If you are NOT using sample data, please specify the following information about your data: 
- `raw_path`: A string of the path to your raw (e.g., intensity) images that were used as the input for segmentation
- `seg_path`: A string of the path where the segmentation outputs are saved
- `location_tosave_fullset_gooddata`: A string to an empty folder that will contain all of the FINAL segmentation files (e.g., it will combine the newly saved edited segmentation files with any of the original segmentation files that did not need editing)
- `raw_file_type`: The raw file type (e.g., ".tiff" or ".czi")
- `seg_file_type`: The segmentation file type (e.g., ".tiff" or ".tif" if you were using infer-subc notebooks or Napari plugin)
- `suffixes`: A list of the endings of your segmentation file names; this usually just includes the segmentation suffix (e.g., 'lyso'), but may also include additional text if the settings file in Napari or the 'name_suffix' in the batch_process_segmentation notebook contained additional text.
- `channels`: A list of indexes of the channels in the raw intensity image used to generate the segmentation corresponding images. The `channels` order should match the order of the `suffixes`. Channel indexes begin at 0 for channel 1. For objects that have no specific channels, please input a value of None.*
- `multichannel_names`: A dictionary with values in suffixes assigned to a list of names to split the multichannel segmentation into. These values are only the suffix values that correspond to images with multiple channels. For example, {'mask': ['nuc', 'cell']} due to the 'mask' file containing both the cell mask and nucleus segmentations.*

In [2]:
### USER INPUT REQUIRED ###
sample_data_type = 'pri-neuron' # Options: None, 'pri-neuron', 'pri-astrocyte', 'iNeuron', 'iPSC'


# Edit locations indicated by "USER SPECIFIED".
raw_data = "USER SPECIFIED"
seg_path = "USER SPECIFIED"

location_tosave_edited_segmentations = "USER SPECIFIED"
location_tosave_fullset_gooddata = "USER SPECIFIED"

raw_file_type = "USER SPECIFIED"
seg_file_type = "USER SPECIFIED"

suffixes = "USER SPECIFIED"
channels = "USER SPECIFIED"
multichannel_names = "USER SPECIFIED"

#### &#x1F6D1; &#x270D; ***Optional* User Input Required:**

&#x1F453; **FYI:** If you ran the batch processing more than once, you can include information about the additional segmentation location and file suffixes here. If you do **NOT** have a second file location, for each object below, please indicate: `None`

***Important:** Only one location for each segmentation type will be used. If `lyso` and `lyso_2` are both specified at the same location in the list, **ONLY** `lyso_2` will be visualized in the below steps.*

In [3]:
#### Optional - USER INPUT REQUIRED ###
seg_path_2 = None

suffixes_2 = [None]

#### &#x1F3C3; **Run code; no user input required**
&#x1F453; **FYI:** This code block will create the two output locations specified above if they don't already exist, and then print the list of raw file names in your raw_path. If using the sample data, the sample data paths are specified based on the setup outlined in the [sample-data_setup.ipynb](/infer-subc/sample_data/sample-data_setup.ipynb) notebook. 

You will want to review each file in the list for accurate segmentations. The next set of code blocks will walk you how to do this.

In [6]:
# If sample_data_type is set to "neuron_1", "astrocyte", "neuron_2" or "iPSC" then the sample data is used and the directories are set
if sample_data_type != None:
    raw_data, seg_path, raw_file_type, seg_file_type, location_tosave_edited_segmentations, location_tosave_fullset_gooddata, suffixes, channels, multichannel_names = sample_input_QC(sample_data_type)

# Create the output directory to save the segmentation outputs in.
if not Path.exists(location_tosave_edited_segmentations):
    Path.mkdir(location_tosave_edited_segmentations)
    print(f"making {location_tosave_edited_segmentations}")
if not Path.exists(location_tosave_fullset_gooddata):
    Path.mkdir(location_tosave_fullset_gooddata)
    print(f"making {location_tosave_fullset_gooddata}")

# Create a list of the file paths for each image in the input folder. Select test image path.
raw_file_list = list_image_files(raw_data, raw_file_type)
pd.set_option('display.max_colwidth', None)
pd.DataFrame({"Image Name":raw_file_list})

                                                                                                                                                                                      Image Name
0  c:\Users\Shannon\Documents\Python_Scripts\SCohen infer-subc\infer-subc\sample_data\example_pri-neuron\raw\20230727_C2-121_conditioned_well 4_cell 3_untreated_Linear unmixing_0_cmle.ome.tiff

### **`STEP 2` - Import and visualize organelle and region segmentations**

#### &#x1F6D1; &#x270D; **User Input Required:**
&#x1F53C; Use the list  above to determine the index of the image you would like to look at. Eventually, you should look at all images. The pipeline below will indicate when you need to return here to repeat for the next image in the list.

In [7]:
#### USER INPUT REQUIRED ###
num = 0

#### &#x1F3C3; **Run code; no user input required**
&#x1F453; **FYI:** This code block will import the segmentation files associated to the raw image you selected above. The raw image and segmentations will be included in a Napari viewer for visual inspection.

In [11]:
raw_img_data, raw_meta_dict = read_czi_image(raw_file_list[num])
viewer.add_image(raw_img_data, name='raw', blending='additive')
print("Image name:")
print(raw_file_list[num].name)
obj_segs = {}

# Importing segmentations
for suffix, channel in zip(suffixes, channels):
    obj = import_inferred_organelle(suffix, raw_meta_dict, Path(seg_path), seg_file_type)
    if suffix not in multichannel_names.keys():
        if len(obj.shape) > 3:
            print(f"{suffix} is multichannel and not in multichannel_names variable, splitting into unnamed separate channels")
            for i in range(int(obj.shape[0])):
                obj_segs[f"{suffix}_{i}"] = (obj[i], channel)
        else:
            obj_segs[suffix] = (obj, channel)
    else:
        if len(obj.shape) <= 3:
            print(f"{suffix} is not multichannel, ignoring")
            obj_segs[suffix] = (obj, channel)
        else:
            for i in range(int(obj.shape[0])):
                obj_segs[multichannel_names[suffix][i]] = (obj[i], channel)

for suffix2, suffix, channel in zip(suffixes_2, suffixes, channels):
    if suffix2 is not None:
        obj = import_inferred_organelle(suffix2, raw_meta_dict, Path(seg_path_2), seg_file_type)
        if suffix not in multichannel_names.keys():
            if len(obj.shape) > 3:
                print(f"{suffix2} is multichannel and not in multichannel_names variable, splitting into unnamed separate channels")
                for i in range(int(obj.shape[0])):
                    obj_segs[f"{suffix}_{i}"] = (obj[i], channel)
            else:
                obj_segs[suffix] = (obj, channel)
        else:
            if len(obj.shape) <= 3:
                print(f"{suffix2} is not multichannel, ignoring")
                obj_segs[suffix] = (obj, channel)
            else:
                for i in range(int(obj.shape[0])):
                    obj_segs[multichannel_names[suffix][i]] = (obj[i], channel)

# Creating colorways
HSV_tuples = [(i/(len(obj_segs.keys())), 1, 1) for i in range(len(obj_segs.keys()))]
RGB_tuples = map(lambda x: colorsys.hsv_to_rgb(*x), HSV_tuples)
col = ["".join("%02X" % round(c*255) for c in rgb) for rgb in RGB_tuples]

for count, suffix in enumerate(obj_segs.keys()):
    cmap = Colormap(["#000000", f"#{col[count]}"], 
                    name=f'{suffix}_cmap')
    channel = obj_segs[suffix][1]
    obj = obj_segs[suffix][0]
    
    if channel is not None:
        viewer.add_image(raw_img_data[channel], name=f'{suffix}_raw', blending='additive')
    viewer.add_image(obj, opacity=0.3, name=f'{suffix}_seg', colormap=cmap)
obj_segs_edit = {key: None for key in obj_segs.keys()}

Image name:
20230727_C2-121_conditioned_well 4_cell 3_untreated_Linear unmixing_0_cmle.ome.tiff
loaded  inferred 4D `masks_A`  from c:\Users\Shannon\Documents\Python_Scripts\SCohen infer-subc\infer-subc\sample_data\example_pri-neuron\seg
loaded  inferred 3D `lyso`  from c:\Users\Shannon\Documents\Python_Scripts\SCohen infer-subc\infer-subc\sample_data\example_pri-neuron\seg
loaded  inferred 3D `mito`  from c:\Users\Shannon\Documents\Python_Scripts\SCohen infer-subc\infer-subc\sample_data\example_pri-neuron\seg
loaded  inferred 3D `golgi`  from c:\Users\Shannon\Documents\Python_Scripts\SCohen infer-subc\infer-subc\sample_data\example_pri-neuron\seg
loaded  inferred 3D `perox`  from c:\Users\Shannon\Documents\Python_Scripts\SCohen infer-subc\infer-subc\sample_data\example_pri-neuron\seg
loaded  inferred 3D `ER`  from c:\Users\Shannon\Documents\Python_Scripts\SCohen infer-subc\infer-subc\sample_data\example_pri-neuron\seg
loaded  inferred 3D `LD`  from c:\Users\Shannon\Documents\Python_Scripts\SCohen infer-subc\infer-subc\sample_data\example_pri-neuron\seg

> #### &#x1F6D1; **STOP: Use the `Napari` window to review all of the segmentations for this image.** &#x1F50E;
>
> **At this point, take note of which segmentations need to be edited, if any. Once you are finished reviewing the segmentations for this image, continue on to the next sections to:**
> 1) Edit the segmentation (if necessary), then
> 2) Quality check the segmentation (if single object), then
> 2) Save the final set of segmentations for this image in a new folder. This step will also save the multichannel files (such as your mask file) as separate files (such as `cell` and `nuc` for the cell mask) in the final analysis location.

### **`STEP 3` - Edit segmentations *(optional)***

This step may be skipped if you are already satisfied with all of your segmentations or have already edited you segmentations with this step before.

Now that you visually inspected your image and the segmentation output files, indicate below which of the segmentations you would like to edit, if any, by typing one of the following options for each segmentation type corresponding to the segmentations listed by the above block of code:
- `True`: for any images you want to edit
- `False`: for any that you do not want to edit

#### &#x1F3C3; **Run code; no user input required**
&#x1F453; **FYI:** The below block of code lists out the segmentations that you have viewed.

In [12]:
print(obj_segs.keys())

dict_keys(['nuc', 'cell', 'lyso', 'mito', 'golgi', 'perox', 'ER', 'LD'])

#### &#x1F6D1; &#x270D; **User Input Required:**

&#x1F53C; Use the above list to reference which True/False statement applies to which segmentation.

In [13]:
obj_edit = [False, False, False, False, False, False, False, False]

#### &#x1F3C3; **Run code; no user input required**

For any image that you have decided to edit, the Napari viewer will be opened one at a time. When you are finished editing the image, close the Napari viewer (do not minimize it), and the code will proceed to the next image. This will repeat until you have cycled through all of your images. If you ever wish to restart editing any of the segmentations from the beginning, you can rerun this block of code after setting the segmentations you do not wish to edit again as false in the obj_edit variable above and rerunning that block of code. 

If you wish to create a segmentation from scratch, you must still edit the layer that you are told to as this is the only layer that will be saved. To start from scratch, you will need to erase any segmentation already present in the image.

In [16]:
if len(obj_edit) != len(obj_segs.keys()):
    print("The number of values in the obj_edit variable is not equal to the number of object segmentations.")
    print("Please adjust the values in the obj_edit variable above, then rerun this block of code.")
if all([edit == False for edit in obj_edit]):
    print("You have selected to not edit any of the segmentations. You can continue to the next step.")
for edit, suffix in zip(obj_edit, obj_segs.keys()):
    if (obj_segs_edit[suffix] is None) or edit:
        obj_segs_edit[suffix] = edit_segmentation(suffix, viewer, edit)
        if edit:
            print(f"Saving your edited {suffix} segmentation to disk...")
            export_inferred_organelle(obj_segs_edit[suffix], suffix, raw_meta_dict, Path(location_tosave_edited_segmentations))
print("If you would like to restart editing any of the segmentations, you can change the obj_edit variable to only select for objects desired to be edited and rerun this block of code.")

You have selected to not edit any of the segmentations. You can continue to the next step.
If you would like to restart editing any of the segmentations, you can change the obj_edit variable to only select for objects desired to be edited and rerun this block of code.

> #### &#x1F6D1; **STOP: Use the `Napari` window to edit chosen segmentations.** &#x1F50E;
>
> **At this point, a `Napari` window will have opened one of the chosen segmentations to edit. Within this Napari window, do NOT change the names of any of the layers. Once you have finished editing the image, do the following:**
> 1) You may manually save the segmentation to another location; however, this occurs automatically and will overwrite your saved segmentations. (optional)
> 2) Close out of all `Napari` windows (do not minimize).
>
> A new `Napari` window will open up so long as there are more segmentations you have chosen to edit.

### **`STEP 4` - Automatically check segmentations**

Below we will run some automatic quality checks on your segmentations to ensure that any images that are designed to be single-objects (such as cell masks) are single objects. This ensures that any editing you may have made will not result in extraneous objects that were unintended to be generated.

List of Quality Checks:
- Ensures only a single object is saved
    - Useful for the cell, nucleus, and soma segmentations
- Ensures the ER remains as a single object

Valid methods of quality checks are as follows:
- `None`: For any images that you don't want to run the quality check filter on or must contain multiple objects
- `'brightest'`: To ensure that the only remaining object in the image is the brightest object (only 1 object remains)
- `'largest'`: To ensure that only the largest object remains after the quality check filter (only 1 object remains)
- `'ER'`: To ensure that all objects in the image are set to the same value. This is most useful for the endoplasmic reticulum segmentation.

&#x1F453; **FYI:** If you skipped `STEP 3` this run, this cell the code will pull from saved copies of your already edited segmentations for this cell; however, for any segmentation you have not edited for this cell already, the code will default to using the original segmentations.

#### &#x1F3C3; **Run code; no user input required**
&#x1F453; **FYI:** The below block of code lists out the segmentations that you have viewed.

In [17]:
print(obj_segs.keys())

dict_keys(['nuc', 'cell', 'lyso', 'mito', 'golgi', 'perox', 'ER', 'LD'])

#### &#x1F6D1; &#x270D; **User Input Required:**

&#x1F53C; Use the above list to reference what value applies to which segmentation.

Now that you have edited your files, indicate below which quality check filter you would like to apply for each segmentation type corresponding to the listed segmentation types above.

In [18]:
quality_filter = ['largest', None, None, None, None, None, None, None]

#### &#x1F3C3; **Run code; no user input required**

> Be sure to follow the instructions provided at the end of the below block of code to determine if you need to return to an earlier block of code or you may proceed. In some instances, you may be allowed to edit your segmentation in the Napari window without needing to rerun the editing process; in these cases, be sure that you only edit the object_seg layer and not the object_seg_filtered layer. 

> The object_seg layer is the segmentation prior to the computer attempting to run a filter to correct any problems with the image. The object_seg_filtered layer is the segmentation after the selected `quality_filter` is applied. Editing the object_seg_filtered layer will result in the computer rerunning the quality check filter on the unfiltered image, resulting in a loss of work.

In [19]:
if len(quality_filter) != len(obj_segs.keys()):
    print("The number of values in the quality filter is not equal to the number of object segmentations.")
    print("Please adjust the values in the quality_filter variable above, then rerun this block of code.")
else:
    filter_table = pd.DataFrame(columns=['QC Method'], index=obj_segs_edit.keys())
    for suffix in obj_segs.keys():
        try:
            obj_segs_edit[suffix] = import_inferred_organelle(suffix, raw_meta_dict, Path(location_tosave_edited_segmentations), seg_file_type)
        except (FileNotFoundError):
            obj_segs_edit[suffix] = obj_segs[suffix][0]
    filtered_obj_segs_edit = {key: None for key in obj_segs_edit.keys()}
    status_table = pd.DataFrame(columns=['Status'], index=obj_segs_edit.keys())
    for suffix, filt in zip(obj_segs_edit.keys(), quality_filter):
        if status_table.at[suffix, 'Status'] is None:
            status_table.at[suffix, 'Status'] = 'N/A'
            filter_table.at[suffix, 'QC Method'] = 'No filter'
        if (filtered_obj_segs_edit[suffix] is None) or (filt is not None):
            try:
                filter_out = filter_segmentation(suffix, filt, obj_segs_edit[suffix], raw_img_data, status_table.at[suffix, 'Status'])
                filtered_obj_segs_edit[suffix] = filter_out[0]
                status_table.at[suffix, 'Status'] = filter_out[1]
                filter_table.at[suffix, 'QC Method'] = filt
            except (ValueError, KeyError):
                print(f"No raw image found for {suffix}, adding the 'raw' layer instead.")
                filter_out = filter_segmentation(suffix, filt, obj_segs_edit[suffix], viewer.layers['raw'].data, status_table.at[suffix, 'Status'])
                filtered_obj_segs_edit[suffix] = filter_out[0]
                status_table.at[suffix, 'Status'] = filter_out[1]
                filter_table.at[suffix, 'QC Method'] = filt
    print("Below are the QC filtering methods that you have chosen:")
    display(filter_table)
    print("Below is the status of the segmentations after the quality control checks:")
    display(status_table)
    if (status_table['Status'] == 'Fail').any():
        print("You have not passed the quality control checks for all segmentations, please make changes to the segmentations that have failed the QC checks.")
        print("These changes may be reediting the image, or rerunning the filter_segmentation function with different filter values.")
        print("Once you have made these changes, please rerun this block of code to revalidate the segmentation status.")
    else:
        print("You have passed the quality control checks for all segmentations.")
        print("Please proceed to the next step.")

`nuc` object not found: c:\Users\Shannon\Documents\Python_Scripts\SCohen infer-subc\infer-subc\sample_data\example_pri-neuron\edit_seg\20230727_C2-121_conditioned_well 4_cell 3_untreated_Linear unmixing_0_cmle.ome-nuc.tiff
`cell` object not found: c:\Users\Shannon\Documents\Python_Scripts\SCohen infer-subc\infer-subc\sample_data\example_pri-neuron\edit_seg\20230727_C2-121_conditioned_well 4_cell 3_untreated_Linear unmixing_0_cmle.ome-cell.tiff
`lyso` object not found: c:\Users\Shannon\Documents\Python_Scripts\SCohen infer-subc\infer-subc\sample_data\example_pri-neuron\edit_seg\20230727_C2-121_conditioned_well 4_cell 3_untreated_Linear unmixing_0_cmle.ome-lyso.tiff
`mito` object not found: c:\Users\Shannon\Documents\Python_Scripts\SCohen infer-subc\infer-subc\sample_data\example_pri-neuron\edit_seg\20230727_C2-121_conditioned_well 4_cell 3_untreated_Linear unmixing_0_cmle.ome-mito.tiff
`golgi` object not found: c:\Users\Shannon\Documents\Python_Scripts\SCohen infer-subc\infer-subc\sample_data\example_pri-neuron\edit_seg\20230727_C2-121_conditioned_well 4_cell 3_untreated_Linear unmixing_0_cmle.ome-golgi.tiff
`perox` object not found: c:\Users\Shannon\Documents\Python_Scripts\SCohen infer-subc\infer-subc\sample_data\example_pri-neuron\edit_seg\20230727_C2-121_conditioned_well 4_cell 3_untreated_Linear unmixing_0_cmle.ome-perox.tiff
`ER` object not found: c:\Users\Shannon\Documents\Python_Scripts\SCohen infer-subc\infer-subc\sample_data\example_pri-neuron\edit_seg\20230727_C2-121_conditioned_well 4_cell 3_untreated_Linear unmixing_0_cmle.ome-ER.tiff
`LD` object not found: c:\Users\Shannon\Documents\Python_Scripts\SCohen infer-subc\infer-subc\sample_data\example_pri-neuron\edit_seg\20230727_C2-121_conditioned_well 4_cell 3_untreated_Linear unmixing_0_cmle.ome-LD.tiff

WARNING: QWindowsWindow::setGeometry: Unable to set geometry 1086x657+3235-838 (frame: 1102x696+3227-869) on QWidgetWindow/"_QtMainWindowClassWindow" on "\\.\DISPLAY3". Resulting geometry: 723x658+3232-852 (frame: 739x697+3224-883) margins: 8, 31, 8, 8 minimum size: 385x495 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=401,534 maxtrack=0,0)
05-May-26 13:17:23 - vispy    - WARNING  - QWindowsWindow::setGeometry: Unable to set geometry 1086x657+3235-838 (frame: 1102x696+3227-869) on QWidgetWindow/"_QtMainWindowClassWindow" on "\\.\DISPLAY3". Resulting geometry: 723x658+3232-852 (frame: 739x697+3224-883) margins: 8, 31, 8, 8 minimum size: 385x495 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=401,534 maxtrack=0,0)

Your nuc segmentation contains MORE THAN ONE nuc object. For quantification, you must only have ONE nuc object, attempting to correct this automatically...
Applying the largest object filter...
The image has been processed to automatically remove any small objects using the largest method.
Head to the Napari window to see your filtered nuc segmentation output!
Note: if further edits are desired, please edit the nuc_seg layer instead of the nuc_seg_filtered layer.
Please close the Napari window to continue.
You appear satsified with the nuc segmentation, saving...
You have chosen not to filter the cell segmentation, returning original segmentation...
You have chosen not to filter the lyso segmentation, returning original segmentation...
You have chosen not to filter the mito segmentation, returning original segmentation...
You have chosen not to filter the golgi segmentation, returning original segmentation...
You have chosen not to filter the perox segmentation, returning original segmentation...
You have chosen not to filter the ER segmentation, returning original segmentation...
You have chosen not to filter the LD segmentation, returning original segmentation...
Below are the QC filtering methods that you have chosen:

      QC Method
nuc     largest
cell       None
lyso       None
mito       None
golgi      None
perox      None
ER         None
LD         None

Below is the status of the segmentations after the quality control checks:

      Status
nuc     Pass
cell     N/A
lyso     N/A
mito     N/A
golgi    N/A
perox    N/A
ER       N/A
LD       N/A

You have passed the quality control checks for all segmentations.
Please proceed to the next step.

> #### &#x1F6D1; **STOP: Review the output of the above block of code.** &#x1F50E;
> 
> **At this point, take note of which segmentations have failed the quality check, if any. Once you are finished reviewing the segmentations for this image, follow the steps the block of code has outlined for you:**
> 1) If you have any segmentations fail quality checks, review the segmentation and potentially re-edit it. 
>    - This may be done in this step or in the previous step. To edit in this step, when viewing the segmentation in the viewer, you may manually edit the object_seg layer and the computer will automatically rerun the quality checks.
> 2) If none of your segmentations fail quality checks, proceed to the next step.

### **`STEP 5` - Save segmentations**

#### &#x1F3C3; **Run code; no user input required**

Now that your segmentations have passed quality control, you can save them using the below block of code.

In [20]:
if (status_table['Status'] == 'Fail').any():
    print("You have not passed the quality control checks for your segmentations. Please return to earlier steps, and adjust your segmentations to meet the assumptions made by the program.")
else:
    for suffix in filtered_obj_segs_edit.keys():
        print(f"Saving your final {suffix} segmentation to disk...")
        export_inferred_organelle(filtered_obj_segs_edit[suffix], suffix, raw_meta_dict, Path(location_tosave_fullset_gooddata))

Saving your final nuc segmentation to disk...
saved file: 20230727_C2-121_conditioned_well 4_cell 3_untreated_Linear unmixing_0_cmle.ome-nuc
Saving your final cell segmentation to disk...
saved file: 20230727_C2-121_conditioned_well 4_cell 3_untreated_Linear unmixing_0_cmle.ome-cell
Saving your final lyso segmentation to disk...
saved file: 20230727_C2-121_conditioned_well 4_cell 3_untreated_Linear unmixing_0_cmle.ome-lyso
Saving your final mito segmentation to disk...
saved file: 20230727_C2-121_conditioned_well 4_cell 3_untreated_Linear unmixing_0_cmle.ome-mito
Saving your final golgi segmentation to disk...
saved file: 20230727_C2-121_conditioned_well 4_cell 3_untreated_Linear unmixing_0_cmle.ome-golgi
Saving your final perox segmentation to disk...
saved file: 20230727_C2-121_conditioned_well 4_cell 3_untreated_Linear unmixing_0_cmle.ome-perox
Saving your final ER segmentation to disk...
saved file: 20230727_C2-121_conditioned_well 4_cell 3_untreated_Linear unmixing_0_cmle.ome-ER
Saving your final LD segmentation to disk...
saved file: 20230727_C2-121_conditioned_well 4_cell 3_untreated_Linear unmixing_0_cmle.ome-LD

> ### 🔁🔁 **Repeat `Steps 2-5` above for *EACH IMAGE* in your dataset.**  
>
> You've now completed the quality check for one image. Repeat these steps for each image in your dataset by selecting the next image in the list at the beginning of `Step 2` above.

-----
### 🎉 **CONGRATULATIONS!! You've successfully completed `infer-subc Part 1 - Segmentation Workflows`.**

Continue on to `infer-subc Part 2 - Organelle Quantification`. An overview is included in the [`2.0_quantification_setup`](..\part_2_quantification\2.0_quantification_setup.ipynb) notebook.