# **Measure Organelle Morphology**

***Prior to this notebook, you should have already run through [2.0_quantification_setup](2.0_quantification_setup.ipynb) and have segmentation outputs of <ins>at least one</ins> organelle.***

In notebooks 2.1 through 2.4, we will go over the implementation of `infer-subc` quantification methods (explained in detail in the `method_...` notebooks) to assess the morphology, interactions, and distribution of organelles at the single-cell level. 

### 📍 **Purpose**
This notebook can be used to measure the `morphology` -- the amount, size, and shape -- of one or more `organelles` from one or more cells. It includes options to:
1. 🦠 Quantify the morphology of *one or more organelle(s)* from <ins>ONE CELL</ins>
2. 🧪 Batch process the morphology of *one or more organelle(s)* from *multiple cells* for a <ins>SINGLE EXPERIMENT</ins>
3. 🧮 Summarize morphology metrics *per cell* across <INS>ONE OR MORE EXPERIMENTS</ins>

Below you will find an [`explanation of steps`](#explanation) for these three quantitative methods. Then, more succinct code blocks are included to [`execute quantification`](#execute) on your own (or sample) data.

### 🍃 **Biological Relevance - Organelle Morphology**
Measurements of organelle morphology are included as part of the organelle signature analysis. These metrics can provide information about the physiology of a cell and its constituent organelles. 

Organelle amounts have been demonstrated to differ between cell types. The cytoplasms of some specialized cell types, like adipocytes, are composed almost entirely of a single large lipid droplet for fat storage[[1]](https://doi.org/10.3390/biom11121906), while other cell types, like muscle cells, have large and elaborate mitochdondrial networks for effective metabolite diffusion during muscle contraction[[2]](https://doi.org/10.1038/nature14614).

Additionally, different organelle morphologies are important to their function. For example, fission and fusion maintain mitochondrial homeostasis by modulating the size and connectedness of the mitochondrial network. A recent study demonstrated that asymmetric fission events resulted in morphologically distinct daughter mitochondria with different fates; the larger mitochondria continued to grow and divide, while the smaller, spherical fragments containing high reactive oxygen species (ROS) were destined for autophagic degradation[[3]](https://doi.org/10.1038/s41586-021-03510-6).

The following morphological measurements are included for each organelle:
- `label`: the unique ID number for the object being measured
- `centroid`: centroid coordinate tuple (row, col, Z)
- `bbox`: bounding box coordinates (min_row, min_col, max_row, max_col); pixels/voxels belonging to the bounding box are in the half-open interval [min_row; max_row) and [min_col; max_col).
- `area`: (or `volume` for 3D z-stack images) area of the region i.e. number of pixels of the region scaled by pixel-area; this metric has the option to be converted into "real world" units using the scale from the metadata.
- `surface_area`: the surface area of the region. For 3D, surface area of a 2D surface mesh of the region (skimage.measure.marching_cubes) using skimage.measure.mesh_surface_area; this metric has the option to be converted into "real world" units using the scale from the metadata.
- `SA_to_volume`: surface area / area (or volume); this metric has the option to be converted into "real world" units using the scale from the metadata.
- `equivalent_diameter`: the diameter of a circle with the same area as the region; this metric has the option to be converted into "real world" units using the scale from the metadata.
- `extent`: ratio of pixels/voxels in the region to pixels/voxels in the total bounding box. Computed as area / (rows * cols)
- `euler_number`: Euler characteristic of the set of non-zero pixels. Computed as number of connected components subtracted by number of holes (input.ndim connectivity). In 3D, number of connected components plus number of holes subtracted by number of tunnels.
- `solidity`: ratio of pixels/voxels in the region to pixels/voxels of the convex hull image.
- `axis_major_length`: the length of the major axis of the ellipse that has the same normalized second central moments as the region; this metric has the option to be converted into "real world" units using the scale from the metadata.
- `mask_volume`: the volume of the mask used to define the area of analysis; usually this will be the cell mask since the analysis is intended to be done at the single-cell level.

The following measures of the intensity images are also included:
- `min_intensity`: value with the least intensity in the region.
- `max_intensity`: value with the greatest intensity in the region.
- `mean_intensity`: value with the mean intensity in the region.
- `standard_deviation_intensity`: the standard deviation of the intensity in the region.

These measurements and definitions are derived from the [`skimage.measure.regionprops()`](https://scikit-image.org/docs/stable/api/skimage.measure.html#skimage.measure.regionprops) function. More in depth information about each measurement can be found there.

*You can learn more about the implementation of regionprops within infer-subc in the [method_morphology](method_morphology.ipynb) notebook.*

-----

## 🗂️ **Table of Contents**
The following sections are included in this notebook:

**IMPORTS AND LOAD IMAGE**

**EXPLANATION OF STEPS** - This section serves as *expository examples* of the functions used to quantify, batch process, and summarize organelle morphology.

🦠 **Quantify the morphology of *one or more organelles* from <ins>ONE IMAGE</ins>**
- **`STEP 1`** - Select mask from regions list, if applicable
- **`STEP 2`** - Loop through the list of organelles to quantify the morphology of each
- **`STEP 3`** - Combine all of the tables together and add the image name as a metadata column
- **`DEFINE`** - The get_organelle_morph() function

🧪 **Batch process *multiple images* from a <ins>SINGLE EXPERIMENT</ins>**
- **`STEP 1`** - Check the output file paths to see if quantification data already exists
- **`STEP 2`** - List images and the segmentation file suffixes that should be collected for each
- **`STEP 3`** - Loop through the list of images and perform the morphology quantification on all organelles
- **`DEFINE`** - The batch_process_org_morph() function

🧮 **Summarize metrics *per image* across <INS>ONE OR MORE EXPERIMENTS</ins>**
- **`STEP 1`** - Get the orgnaelle morphology .csv files
- **`STEP 2`** - Summarize the mean, median, and standard deviation of each metric per image/mask region
- **`STEP 3`** - Ensure all organelles included in the analysis are represented and fill NA values with 0 as needed
- **`STEP 4`** - Unstack the organelle names and save file
- **`DEFINE`** - The batch_org_morph_summary_stats() function

**EXECUTE QUANTIFICATION** - Once you understand how the functions work, this section can be used to quantify your data in a quick and easy way.
- **`STEP 1`:** 🧪 **Batch process *multiple images* from a <ins>SINGLE EXPERIMENT</ins>**
- **`STEP 2`:** 🧮 **Summarize metrics *per image* across <INS>ONE OR MORE EXPERIMENTS</ins>**

-----
---------------------
## **IMPORTS AND LOAD IMAGE**
Details about the functions included in this subsection are outlined in the [`2.0_quantification_setup`](2.0_quantification_setup.ipynb) notebook. Please visit that notebook first if you are confused about any of the code included here.

In [1]:
from typing import List, Union
from pathlib import Path
import os
import time
import warnings
import tempfile
from IPython.display import HTML

from infer_subc.core.img import *

import numpy as np
import pandas as pd
import napari
from napari.utils.notebook_display import nbscreenshot

from infer_subc.quantification.morphology import get_morphology_metrics, batch_process_org_morph, batch_org_morph_summary_stats
from infer_subc.utils.batch import list_image_files, find_segmentation_tiff_files
from infer_subc.core.file_io import read_czi_image, read_tiff_image, export_inferred_organelle
from infer_subc.quantification.skeletonization import create_skel, get_skeleton_metrics

pd.set_option('display.max_columns', None)

#### &#x1F3C3; **Run code; no user input required**

#### &#x1F6D1; &#x270D; **User Input Required:**

Please specify the following information about your data: `raw_img_type`, `data_root_path`, `raw_data_path`, `seg_data_path`, and `quant_data_path`.

In [2]:
#### NRM TESTING ###
raw_img_type = ".tiff"
data_root_path = Path("C:/Users/redre/Documents/CohenLab/scohen_lab_repo/infer-subc/sample_data/example_quant")
raw_data_path = data_root_path / "raw"
seg_data_path = data_root_path / "seg"
quant_data_path = data_root_path / "quant"

In [3]:
# #### USER INPUT REQUIRED ###
# raw_img_type = ".czi"
# data_root_path = Path(os.path.expanduser("~")) / "Documents/Python_Scripts/Infer-subc"
# raw_data_path = data_root_path / "raw_two"
# seg_data_path = data_root_path / "out_two"
# quant_data_path = data_root_path / "quant_two"

#### &#x1F3C3; **Run code; no user input required**

In [4]:
# Create the output directory to save the segmentation outputs in.
if not Path.exists(quant_data_path):
    Path.mkdir(quant_data_path)
    print(f"making {quant_data_path}")

# Create a list of the file paths for each image in the input folder. Select test image path.
raw_img_file_list = list_image_files(raw_data_path,raw_img_type)
pd.set_option('display.max_colwidth', None)
pd.DataFrame({"Image Name":raw_img_file_list})

                                                                                                                                            Image Name
0  C:\Users\redre\Documents\CohenLab\scohen_lab_repo\infer-subc\sample_data\example_quant\raw\05052022_astro_control_2_Linear unmixing_0_cmle.ome.tiff

#### &#x1F6D1; &#x270D; **User Input Required:**

Use the list above to specify which image you wish to analyze based on its index: `test_img_n`

In [5]:
#### USER INPUT REQUIRED ###
test_img_n = 0

#### &#x1F3C3; **Run code; no user input required**

In [6]:
# Read in the image and metadata as an ndarray and dictionary from the test image selected above. 
test_img_name = raw_img_file_list[test_img_n]
img_data,meta_dict = read_czi_image(test_img_name)

# Define some of the metadata features.
channel_names = meta_dict['name']
meta = meta_dict['metadata']['aicsimage']
scale = meta_dict['scale']
channel_axis = meta_dict['channel_axis']
file_path = meta_dict['file_name']

print("Metadata information")
print(f"File path: {file_path}")
for i in list(range(len(channel_names))):
    print(f"Channel {i} name: {channel_names[i]}")
print(f"Scale (ZYX): {scale}")
print(f"Channel axis: {channel_axis}")

Metadata information
File path: C:\Users\redre\Documents\CohenLab\scohen_lab_repo\infer-subc\sample_data\example_quant\raw\05052022_astro_control_2_Linear unmixing_0_cmle.ome.tiff
Channel 0 name: 05052022_astro_control_2_Linear unmixing_0_cmle.ome :: Channel:0
Channel 1 name: 05052022_astro_control_2_Linear unmixing_0_cmle.ome :: Channel:1
Channel 2 name: 05052022_astro_control_2_Linear unmixing_0_cmle.ome :: Channel:2
Channel 3 name: 05052022_astro_control_2_Linear unmixing_0_cmle.ome :: Channel:3
Channel 4 name: 05052022_astro_control_2_Linear unmixing_0_cmle.ome :: Channel:4
Channel 5 name: 05052022_astro_control_2_Linear unmixing_0_cmle.ome :: Channel:5
Scale (ZYX): (0.396091, 0.079947, 0.079947)
Channel axis: 0

#### &#x1F6D1; &#x270D; **User Input Required:**

Specify the following information about the segmentation files: - `org_file_names`, `org_channels_ordered`, `regions_file_names`, `suffix_separator`, and `mask_name`.

In [7]:
#### NRM TESTING ###
# org_file_names = ["lyso", "mito", "golgi", "perox", "ER", "LD"]
# org_channels_ordered = [3, 4, 2, 5, 1, 0]
org_file_names = ["mito", "golgi", "ER"]
org_channels_ordered = [4, 2, 1]
regions_file_names = ["cell", "nuc"]
suffix_separator = ""
mask_name = "cell"

In [8]:
# #### USER INPUT REQUIRED ###
# org_file_names = ["lyso", "mito", "golgi", "perox", "ER", "LD"]
# org_channels_ordered = [1, 2, 3, 4, 5, 6]
# regions_file_names = ["cell", "nuc"]
# suffix_separator = "-20230426_test"
# mask_name = "cell"

#### &#x1F3C3; **Run code; no user input required**

In [9]:
# find file paths for segmentations
all_suffixes = org_file_names + regions_file_names
filez = find_segmentation_tiff_files(file_path, all_suffixes, seg_data_path, suffix_separator)

# read the segmentation and masks/regions files into memory
organelles = [read_tiff_image(filez[org]) for org in org_file_names]
regions = [] 
for m in regions_file_names:
    mfile = read_tiff_image(filez[m])
    regions.append(mfile)

# match the intensity channels to the segmentation files
intensities = [img_data[ch] for ch in org_channels_ordered]

# open viewer and add images
viewer = napari.Viewer()
for r, reg in enumerate(regions_file_names):
    viewer.add_image(regions[r],
                     scale=scale,
                     name=f"{reg} mask")

# colors = ["red", "bop orange", "yellow", "green", "blue", "cyan", "magenta", "bop purple"]
for o, org in enumerate(org_file_names):
    viewer.add_image(intensities[o],
                     scale=scale,
                     name=f"{org} intensity channel")
    viewer.add_labels(organelles[o],
                      scale=scale,
                      name=f"{org} segmentation")
viewer.grid.enabled = True
viewer.reset_view()

print("The following matching files were found and can now be viewed in Napari:")
filez

The following matching files were found and can now be viewed in Napari:

{'raw': WindowsPath('C:/Users/redre/Documents/CohenLab/scohen_lab_repo/infer-subc/sample_data/example_quant/raw/05052022_astro_control_2_Linear unmixing_0_cmle.ome.tiff'),
 'mito': WindowsPath('C:/Users/redre/Documents/CohenLab/scohen_lab_repo/infer-subc/sample_data/example_quant/seg/05052022_astro_control_2_Linear unmixing_0_cmle.ome-mito.tiff'),
 'golgi': WindowsPath('C:/Users/redre/Documents/CohenLab/scohen_lab_repo/infer-subc/sample_data/example_quant/seg/05052022_astro_control_2_Linear unmixing_0_cmle.ome-golgi.tiff'),
 'ER': WindowsPath('C:/Users/redre/Documents/CohenLab/scohen_lab_repo/infer-subc/sample_data/example_quant/seg/05052022_astro_control_2_Linear unmixing_0_cmle.ome-ER.tiff'),
 'cell': WindowsPath('C:/Users/redre/Documents/CohenLab/scohen_lab_repo/infer-subc/sample_data/example_quant/seg/05052022_astro_control_2_Linear unmixing_0_cmle.ome-cell.tiff'),
 'nuc': WindowsPath('C:/Users/redre/Documents/CohenLab/scohen_lab_repo/infer-subc/sample_data/example_quant/seg/05052022_astro_control_2_Linear unmixing_0_cmle.ome-nuc.tiff')}

------
-----
## **EXPLANATION OF STEPS** <a id='explanation'></a>

-----
### 🦠 **Quantify one or more organelles from <ins>ONE IMAGE</ins>**

#### **`STEP 1` - Select mask from regions list, if applicable**

##### &#x1F3C3; **Run code; no user input required**

&#x1F453; **FYI:** The analysis outlined below can be carried out on the entire image (`mask_name`=None), or one a single region within the image (`mask_name`={region-suffix}). For example, you may wish to ensure the analysis is carried out at the single cell level, in which case you would provide the cell segmentation file as the mask. In the cell below, the cell mask is selected from the `regions` list created above. During the analysis, any organelles outside of the cell will be ignored.

In [10]:
# specify the mask image to use during quantification
if regions_file_names is None or regions is None:
    print("No regions provided. No mask will be applied before analysis.")
    mask = None
elif mask_name is None or mask_name not in regions_file_names:
    if mask_name is not None:
        raise ValueError(f"Mask '{mask_name}' not found. No mask will be applied before analysis.")
    mask = None
    mask_name = None
else:
    mask = regions[regions_file_names.index(mask_name)]

# add mask to napari for visual inspection
if mask is not None:
    viewer.layers.clear()
    viewer.add_image(img_data, scale=scale, name="Intensity Image")
    viewer.add_labels(mask, scale=scale, name="Mask")
    viewer.grid.enabled = False
    viewer.reset_view()
    print("Mask added to viewer for inspection.")

Mask added to viewer for inspection.

#### **`STEP 2` - Loop through the list of organelles to quantify the morphology of each**

##### &#x1F6D1; &#x270D; **User Input Required:**

&#x1F453; **FYI:** The block of code below first merges the intensity channels for each organelle together as a single numpy array that will be used during mophorology quantification. Then, it loops through the list of organelles carrying out the following steps for each:
1) The organelle segmentation image is selected from the list of segmentations specified above
2) A check is done to ensure the segmentation files are formatted corrected (e.g., the ER should only include on object)
3) The `get_morphology_metrics()` function from the [method_morphology.ipynb](method_morphology.ipynb) is carried out
4) If the organelle was listed for skeletonization, the `get_skeleton_metics` function from the [method_skeletonization.ipynb](method_skeletonization.ipynb) is also carried out

Specify if the which organelles skeletonization should be carried out on:
- `include_skel`: List of strings indicate which organelles will undergo skeletonization. The strings should match the names of the corresponding segmentation files. If you want to completely skip skeletonization, leave the list empty

- `all_skel_tab` : Whether or not to also putput branch and node tables along with skeletonization metrics (if include_skel = False, this input is ignored)

In [11]:
# list of segmentations to be skeletonized in addition to the morphology metrics
include_skel = ["mito", "golgi", "ER"] # to skip skeletonization, set to [] (empty list)

all_skel_tab = True

> ***IMPORTANT**: The solidity measurement included in the `get_morphology_metrics()` function may cause an error for objects that are very small. It depends on the convex hull measurement which is computed as 0 when the object volume is very small; the solidity value is then output in the table as `inf` (infinity). The following error message will be included:*
> ```python
> UserWarning: Failed to get convex hull image. Returning empty image, see error message below:
> ```
>*The error messages have been suppressed as part of `get_morphology_metrics()` to reduce clutter in the output, but a warning is still printed to indicate when this happens.*

In [12]:
if intensities is None:
    intensity_img = None
    print("No intensity images provided. Morphology metrics that require intensity images will not be calculated.")
else:
    intensity_img = np.stack(intensities, axis=0)

# empty list to collect the morphology data for each organelle
org_tabs = []
skel_arr_imgs = {}
# additional skeleton tables if include_skel and all_skel_tab are both True
branch_tabs = []
node_tabs = []

if set(include_skel) - set(org_file_names) != set():
    raise ValueError(f"All segmentations specified for skeletonization must be included in the list of organelle file names. Names not in org_file_names: {set(include_skel) - set(org_file_names)}.")

# loop through the list of organelles and run the get_morphology_metrics function
for j, target in enumerate(org_file_names):    
    # select segmentation and if ER, ensure it is only one object
    if target == 'ER':
        org_obj = (organelles[j] > 0).astype(np.uint16)
    else:
        org_obj = organelles[j]
    
    # run get_morphology_metrics function to output a table of measurements
    org_metrics = get_morphology_metrics(segmentation_img=org_obj, 
                                         seg_name=target, 
                                         intensity_img=intensity_img, 
                                         intensity_ch_names=org_file_names, # default to org_file_names since they are oriented the same way above
                                         channel_axis=0, # default to 0 because intensities are merged from list on axis 0
                                         mask=mask,
                                         mask_name=mask_name,
                                         scale=scale)
    
    # run get_skeleton_metrics function to add skeleton quantification if organelle is in include_skel list
    if target in include_skel:
        skel_arr = create_skel(org_obj)
        if np.sum(skel_arr.astype(bool))>1:
            if all_skel_tab:
                    branch_table, node_table, skel_metrics = get_skeleton_metrics(org_skel_arr=skel_arr,
                                                        seg_name=target, 
                                                        segmentation=org_obj,
                                                        mask=mask,
                                                        mask_name=mask_name,
                                                        scale=scale,
                                                        output_all_tables = True)
                    
                    branch_table.insert(0, "branch_id", branch_table.index)
                    branch_table = branch_table.reset_index(drop=True)
                    branch_table.insert(0, "object", target)
                    branch_table.insert(0, "scale", str(scale))
                    branch_table.insert(0, column="mask_name", value=mask_name)
                    branch_table = branch_table.rename(columns={"skel_obj_id": "label"})

                    node_table.insert(0, "object", target)
                    node_table.insert(0, "scale", str(scale))
                    node_table.insert(0, column="mask_name", value=mask_name)
                    node_table = node_table.rename(columns={"obj_id": "label"})

                    branch_tabs.append(branch_table)
                    node_tabs.append(node_table)
            else:
                    skel_metrics = get_skeleton_metrics(org_skel_arr=skel_arr,
                                                        seg_name=target,
                                                        segmentation=org_obj,
                                                        mask=mask,
                                                        mask_name=mask_name,
                                                        scale=scale,
                                                        output_all_tables = False)
                
        else:
            print(f"Skeletonization will not be carried out for {target} because less than two voxels are present in the skeleton array")
            skel_arr = None
        skel_arr_imgs[target] = skel_arr
       
       # Rename skeleton metric columns to distingush from morphology metrics
        skel_cols = [col for col in skel_metrics.columns[:6]]
        for i in skel_metrics.columns[6:]:
             skel_cols.append("skel_" + i)
        skel_metrics.columns = skel_cols

       # dropping list related measurements as they do not add interpretability and cause tables to be very tall and difficult to read
        skel_drop = ['skel_branch_ids',
                    'skel_brh_type_0_id',
                    'skel_brh_type_1_ids',
                    'skel_brh_type_2_ids',
                    'skel_brh_type_3_ids',
                    'skel_point_ids']
       
        org_metrics = pd.merge(org_metrics, skel_metrics.drop(columns=skel_drop), on=['mask_name','scale','object', 'label'], validate='one_to_one')

    # add table to list above
    org_tabs.append(org_metrics)

# print each table separately
for i, org in enumerate(org_file_names):
    print(f"{org} morphology metrics table:")
    display(org_tabs[i])

Warning(s) suppressed while quantifying mito. See 'method_morphology.ipynb' notebook for more details.
Warning(s) suppressed while quantifying golgi. See 'method_morphology.ipynb' notebook for more details.
Warning(s) suppressed while quantifying ER. See 'method_morphology.ipynb' notebook for more details.
mito morphology metrics table:

Empty DataFrame
Columns: [mask_name, scale, object, label, centroid-0, centroid-1, centroid-2, bbox-0, bbox-1, bbox-2, bbox-3, bbox-4, bbox-5, volume, surface_area, SA_to_volume_ratio, equivalent_diameter, extent, euler_number, solidity, axis_major_length, min_intensity-mito-ch, min_intensity-golgi-ch, min_intensity-ER-ch, max_intensity-mito-ch, max_intensity-golgi-ch, max_intensity-ER-ch, mean_intensity-mito-ch, mean_intensity-golgi-ch, mean_intensity-ER-ch, standard_deviation_intensity-mito-ch, standard_deviation_intensity-golgi-ch, standard_deviation_intensity-ER-ch, cell_volume, skel_type, skel_type_num, skel_brh_count, skel_min_brh_length, skel_max_brh_length, skel_ave_brh_length, skel_sd_brh_length, skel_med_brh_length, skel_total_length, skel_brh_type_0_tot, skel_brh_type_1_tot, skel_brh_type_2_tot, skel_brh_type_3_tot, skel_comp_count, skel_node_count, skel_abs_punc_count, skel_ep_count, skel_jn_count, skel_ave_jn_deg, skel_max_deg, skel_mean_brh_str, skel_med_brh_str, skel_sd_brh_str, skel_width]
Index: []

golgi morphology metrics table:

Empty DataFrame
Columns: [mask_name, scale, object, label, centroid-0, centroid-1, centroid-2, bbox-0, bbox-1, bbox-2, bbox-3, bbox-4, bbox-5, volume, surface_area, SA_to_volume_ratio, equivalent_diameter, extent, euler_number, solidity, axis_major_length, min_intensity-mito-ch, min_intensity-golgi-ch, min_intensity-ER-ch, max_intensity-mito-ch, max_intensity-golgi-ch, max_intensity-ER-ch, mean_intensity-mito-ch, mean_intensity-golgi-ch, mean_intensity-ER-ch, standard_deviation_intensity-mito-ch, standard_deviation_intensity-golgi-ch, standard_deviation_intensity-ER-ch, cell_volume, skel_type, skel_type_num, skel_brh_count, skel_min_brh_length, skel_max_brh_length, skel_ave_brh_length, skel_sd_brh_length, skel_med_brh_length, skel_total_length, skel_brh_type_0_tot, skel_brh_type_1_tot, skel_brh_type_2_tot, skel_brh_type_3_tot, skel_comp_count, skel_node_count, skel_abs_punc_count, skel_ep_count, skel_jn_count, skel_ave_jn_deg, skel_max_deg, skel_mean_brh_str, skel_med_brh_str, skel_sd_brh_str, skel_width]
Index: []

ER morphology metrics table:

Empty DataFrame
Columns: [mask_name, scale, object, label, centroid-0, centroid-1, centroid-2, bbox-0, bbox-1, bbox-2, bbox-3, bbox-4, bbox-5, volume, surface_area, SA_to_volume_ratio, equivalent_diameter, extent, euler_number, solidity, axis_major_length, min_intensity-mito-ch, min_intensity-golgi-ch, min_intensity-ER-ch, max_intensity-mito-ch, max_intensity-golgi-ch, max_intensity-ER-ch, mean_intensity-mito-ch, mean_intensity-golgi-ch, mean_intensity-ER-ch, standard_deviation_intensity-mito-ch, standard_deviation_intensity-golgi-ch, standard_deviation_intensity-ER-ch, cell_volume, skel_type, skel_type_num, skel_brh_count, skel_min_brh_length, skel_max_brh_length, skel_ave_brh_length, skel_sd_brh_length, skel_med_brh_length, skel_total_length, skel_brh_type_0_tot, skel_brh_type_1_tot, skel_brh_type_2_tot, skel_brh_type_3_tot, skel_comp_count, skel_node_count, skel_abs_punc_count, skel_ep_count, skel_jn_count, skel_ave_jn_deg, skel_max_deg, skel_mean_brh_str, skel_med_brh_str, skel_sd_brh_str, skel_width]
Index: []

#### **`STEP 3` - Combine all of the tables together and add the image name as a metadata column**

##### &#x1F3C3; **Run code; no user input required**

&#x1F453; **FYI:** This code block combines the above tables together so that each organelle object is listed as a separate column in a single table. A new column is then added to specify which image the data is from.

In [13]:
# combine the lists for each organelle into one table
final_org_tab = pd.concat(org_tabs, ignore_index=True)

# add a new column to list the name of the image these data are derived from 
final_org_tab.insert(loc=0,column='image_name',value=file_path.stem)

if include_skel and all_skel_tab:
    final_branch_tab = pd.concat(branch_tabs)
    final_branch_tab.insert(0, "image_name", file_path.stem)
    final_node_tab = pd.concat(node_tabs)
    final_node_tab.insert(0, "image_name", file_path.stem)

# print table for inspection
display(final_org_tab)

Empty DataFrame
Columns: [image_name, mask_name, scale, object, label, centroid-0, centroid-1, centroid-2, bbox-0, bbox-1, bbox-2, bbox-3, bbox-4, bbox-5, volume, surface_area, SA_to_volume_ratio, equivalent_diameter, extent, euler_number, solidity, axis_major_length, min_intensity-mito-ch, min_intensity-golgi-ch, min_intensity-ER-ch, max_intensity-mito-ch, max_intensity-golgi-ch, max_intensity-ER-ch, mean_intensity-mito-ch, mean_intensity-golgi-ch, mean_intensity-ER-ch, standard_deviation_intensity-mito-ch, standard_deviation_intensity-golgi-ch, standard_deviation_intensity-ER-ch, cell_volume, skel_type, skel_type_num, skel_brh_count, skel_min_brh_length, skel_max_brh_length, skel_ave_brh_length, skel_sd_brh_length, skel_med_brh_length, skel_total_length, skel_brh_type_0_tot, skel_brh_type_1_tot, skel_brh_type_2_tot, skel_brh_type_3_tot, skel_comp_count, skel_node_count, skel_abs_punc_count, skel_ep_count, skel_jn_count, skel_ave_jn_deg, skel_max_deg, skel_mean_brh_str, skel_med_brh_str, skel_sd_brh_str, skel_width]
Index: []

#### **`DEFINE` - The get_organelle_morph() function**

In [16]:
def _get_org_morphology(source_file_path: str,
                        list_obj_names: List[str],
                        list_obj_segs: List[np.ndarray],
                        list_intensity_img: Union[List[np.ndarray], None]=None,
                        list_region_names: Union[List[str], None]=None,
                        list_region_segs: Union[List[np.ndarray], None]=None,
                        mask_name: Union[str, None]=None,
                        scale: Union[tuple,None] = None,
                        include_skel: Union[List[str], None] = [],
                        all_skel_tab: bool = False):
    """
    Measure the amount, size, and shape of multiple organelles from a single cell

    Parameters:
    ----------
    source_file: str
        Path to the source image file. This will be used as part of the metadata information in the output table. 
        The input images are not derived from this path, but rather are provided directly as arrays in the list_obj_segs and 
        list_intensity_img variables below.
    list_obj_names: List[str]
        List of organelle names. These names should match the suffix on the segmentation image files.
    list_obj_segs: List[np.ndarray]
        List of 3D organelle segmentation arrays matching the order included in list_obj_names.
    list_intensity_img: Union[List[np.ndarray], None]
        List of 3D intensity channels from the raw image used to produce the segmentations in list_obj_segs.
        The order here should match the list_obj_segs and list_obj_names variables.
        Additional intensity channels not matching one of the segmented organelles/included in list_obj_names should not be included.
        If no intensity analysis is to be included, specify None here.
    list_region_names: Union[List[str], None]
        List of segmented region/mask names. These names should match the suffix on the segmentation image files.
        This should include:
            - a mask segmentation, such as the cell mask, for masking during all interactions analysis; else, the entire image will be 
            quantified. Only one objects per mask image will be analyzed. If there are more than one included, they will be combined 
            prior to analysis and the entire region will be quantified. If no mask is provided, the entire image will be quantified.
            - a centering object, such as the nucleus, for distribution analysis; else the center of the mask region will be used as 
            the XY distribution centering point if distribution analysis is included.
    list_region_segs: Union[List[np.ndarray], None]
        List of 3D region segmentation arrays matching the order specified in list_region_names. Specify None if no regions are provided.
    mask_name: Union[str, None]
        Name of the region to use as the mask for analysis; if not specified, the entire image will be quantified.
    scale: Union[tuple,None] = None
        a tuple that contains the real world dimensions for each dimension in the image (Z, Y, X)
    include_skel: Union[List[str], None]
             List of 3D organelle segmentation arrays to be skeletonized in addition to morphology metrics.
             The names should match those included in list_obj_names. If no skeletonization is to be included, specify [] (empty list).
    all_skel_tab: bool
        Whether to output all skeleton tables (True) or just the skeleton metrics table (False).

    Returns:
    ----------
    Dataframe of measurements of organelle morphology

    """
    # Validate inputs
    if not list_obj_names:
        raise ValueError("list_obj_names cannot be empty")
    if len(list_obj_names) != len(list_obj_segs):
        raise ValueError(f"Mismatch: {len(list_obj_names)} items in list_obj_names but {len(list_obj_segs)} items in list_obj_segs")
    if list_intensity_img and len(list_obj_names) != len(list_intensity_img):
        raise ValueError(f"Mismatch: {len(list_obj_names)} items in list_obj_names but {len(list_intensity_img)} items in list_intensity_img")
    if list_region_names and list_region_segs and len(list_region_names) != len(list_region_segs):
        raise ValueError(f"Mismatch: {len(list_region_names)} items in list_region_names but {len(list_region_segs)} items in list_region_segs")
    
    if isinstance(source_file_path, str): source_file_path = Path(source_file_path)
    print(f"Quantifying organelle morphology from {source_file_path.name}")

    # specify the mask image to use during quantification
    if list_region_names is None or list_region_segs is None:
        print("No regions provided. No mask will be applied before analysis.")
        mask = None
    elif mask_name is None or mask_name not in list_region_names:
        if mask_name is not None:
            raise ValueError(f"Mask '{mask_name}' not found. No mask will be applied before analysis.")
        mask = None
        mask_name = None
    else:
        mask = list_region_segs[list_region_names.index(mask_name)]
    
    # merge intensity images to create a single np.ndarray
    if list_intensity_img is None:
        intensity_img = None
        print("No intensity images provided. Morphology metrics that require intensity images will not be calculated.")
    else:
        intensity_img = np.stack(list_intensity_img, axis=0)

    # empty list to collect a morphology data for each organelle
    org_tabs = []
    skel_arr_imgs = {}
    # additional skeleton tables if include_skel and all_skel_tab are both True
    branch_tabs = []
    node_tabs = []

    # loop through the list of organelles and run the get_morphology_metrics function
    for j, target in enumerate(list_obj_names):        
        # select segmentation and if ER, ensure it is only one object
        if target == 'ER':
            org_obj = (list_obj_segs[j] > 0).astype(np.uint16)  
        else:
            org_obj = list_obj_segs[j]
        
        # run get_morphology_metrics function to output a table of measurements
        org_metrics = get_morphology_metrics(segmentation_img=org_obj, 
                                            seg_name=target,
                                            intensity_img=intensity_img, 
                                            intensity_ch_names=list_obj_names,
                                            channel_axis=0, # default to 0 because intensities are merged from list on axis 0
                                            mask=mask,
                                            mask_name=mask_name,
                                            scale=scale)
        
        # run get_skeleton_metrics function to add skeleton quantification if organelle is in include_skel list
        if target in include_skel:
            skel_arr = create_skel(org_obj)
            if np.sum(skel_arr.astype(bool))>1:
                if all_skel_tab:
                        branch_table, node_table, skel_metrics = get_skeleton_metrics(org_skel_arr=skel_arr,
                                                            seg_name=target, 
                                                            segmentation=org_obj,
                                                            mask=mask,
                                                            mask_name=mask_name,
                                                            scale=scale,
                                                            output_all_tables = True)
                        
                        branch_table.insert(0, "branch_id", branch_table.index)
                        branch_table = branch_table.reset_index(drop=True)
                        branch_table.insert(0, "object", target)
                        branch_table.insert(0, "scale", str(scale))
                        branch_table.insert(0, column="mask_name", value=mask_name)
                        branch_table = branch_table.rename(columns={"skel_obj_id": "label"})

                        node_table.insert(0, "object", target)
                        node_table.insert(0, "scale", str(scale))
                        node_table.insert(0, column="mask_name", value=mask_name)
                        node_table = node_table.rename(columns={"obj_id": "label"})

                        branch_tabs.append(branch_table)
                        node_tabs.append(node_table)
                else:
                        skel_metrics = get_skeleton_metrics(org_skel_arr=skel_arr,
                                                            seg_name=target, 
                                                            segmentation=org_obj,
                                                            mask=mask,
                                                            mask_name=mask_name,
                                                            scale=scale,
                                                            output_all_tables = False)
            else:
                print(f"Skeletonization will not be carried out for {target} because less than two voxels are present in the skeleton array")
                skel_arr = None
            skel_arr_imgs[target] = skel_arr
            
            # Rename skeleton metric columns to distingush from morphology metrics
            skel_cols = [col for col in skel_metrics.columns[:6]]
            for i in skel_metrics.columns[6:]:
                skel_cols.append("skel_" + i)
            skel_metrics.columns = skel_cols

            # dropping list related measurements as they do not add interpretability and cause tables to be very tall and difficult to read
            skel_drop = ['skel_branch_ids',
                    'skel_brh_type_0_id',
                    'skel_brh_type_1_ids',
                    'skel_brh_type_2_ids',
                    'skel_brh_type_3_ids',
                    'skel_point_ids']
            
            org_metrics = pd.merge(org_metrics, skel_metrics.drop(columns=skel_drop), on=['mask_name','scale','object', 'label'], validate='one_to_one')

        # add table to list above
        org_tabs.append(org_metrics)

    # combine the lists for each organelle into one table
    final_org_tab = pd.concat(org_tabs, ignore_index=True)

    # add a new column to list the name of the image these data are derived from 
    final_org_tab.insert(loc=0,column='image_name',value=source_file_path.stem)
    
    if include_skel and all_skel_tab:
        final_branch_tab = pd.concat(branch_tabs)
        final_branch_tab.insert(0, "image_name", source_file_path.stem)
        final_node_tab = pd.concat(node_tabs)
        final_node_tab.insert(0, "image_name", source_file_path.stem)
        return final_org_tab, final_branch_tab, final_node_tab, skel_arr_imgs
    else:
        return final_org_tab, skel_arr_imgs

#### &#x1F3C3; **Run code; no user input required**

&#x1F453; **FYI:** This code block applies the function above to your test image. The settings specified above are applied here.

In [18]:
# test function above
if include_skel and all_skel_tab:
    org_morph_tab, branch_tab, node_tab, skel_arrs = _get_org_morphology(source_file_path = file_path,
                                     list_obj_names = org_file_names,
                                     list_obj_segs = organelles,
                                     list_intensity_img = intensities, 
                                     list_region_names = regions_file_names,
                                     list_region_segs = regions,
                                     mask_name=mask_name,
                                     scale=scale,
                                     include_skel=include_skel,
                                     all_skel_tab=all_skel_tab)
    
    print("Organelle morphology table:")
    display(org_morph_tab)
    print("Skeleton branch table:")
    display(branch_tab)
    print("Skeleton node table:")
    display(node_tab)
else:
    org_morph_tab, skel_arrs = _get_org_morphology(source_file_path = file_path,
                                        list_obj_names = org_file_names,
                                        list_obj_segs = organelles,
                                        list_intensity_img = intensities, 
                                        list_region_names = regions_file_names,
                                        list_region_segs = regions,
                                        mask_name=mask_name,
                                        scale=scale,
                                        include_skel=include_skel,
                                        all_skel_tab=all_skel_tab)
    print("Organelle morphology table:")
    display(org_morph_tab)

# check is function output matches previous output
print(f"\nThe output here matches the output from the individual steps above: {org_morph_tab.equals(final_org_tab)}")
if include_skel:
    print("Skeleton images:", all([np.array_equal(skel_arr_imgs[key], val) for key, val in skel_arrs.items()]))
    if all_skel_tab:
        print(f"\nThe output here matches the output from the individual steps above for the branch table: {branch_tab.equals(final_branch_tab)}")
        print(f"\nThe output here matches the output from the individual steps above for the node table: {node_tab.equals(final_node_tab)}")

Quantifying organelle morphology from 05052022_astro_control_2_Linear unmixing_0_cmle.ome.tiff
Warning(s) suppressed while quantifying mito. See 'method_morphology.ipynb' notebook for more details.
Warning(s) suppressed while quantifying golgi. See 'method_morphology.ipynb' notebook for more details.
Warning(s) suppressed while quantifying ER. See 'method_morphology.ipynb' notebook for more details.
Organelle morphology table:

Empty DataFrame
Columns: [image_name, mask_name, scale, object, label, centroid-0, centroid-1, centroid-2, bbox-0, bbox-1, bbox-2, bbox-3, bbox-4, bbox-5, volume, surface_area, SA_to_volume_ratio, equivalent_diameter, extent, euler_number, solidity, axis_major_length, min_intensity-mito-ch, min_intensity-golgi-ch, min_intensity-ER-ch, max_intensity-mito-ch, max_intensity-golgi-ch, max_intensity-ER-ch, mean_intensity-mito-ch, mean_intensity-golgi-ch, mean_intensity-ER-ch, standard_deviation_intensity-mito-ch, standard_deviation_intensity-golgi-ch, standard_deviation_intensity-ER-ch, cell_volume, skel_type, skel_type_num, skel_brh_count, skel_min_brh_length, skel_max_brh_length, skel_ave_brh_length, skel_sd_brh_length, skel_med_brh_length, skel_total_length, skel_brh_type_0_tot, skel_brh_type_1_tot, skel_brh_type_2_tot, skel_brh_type_3_tot, skel_comp_count, skel_node_count, skel_abs_punc_count, skel_ep_count, skel_jn_count, skel_ave_jn_deg, skel_max_deg, skel_mean_brh_str, skel_med_brh_str, skel_sd_brh_str, skel_width]
Index: []

Skeleton branch table:

,image_name,mask_name,scale,object,branch_id,label,point_id_src,point_id_dst,deg_src,deg_dst,branch_type,image_coord_src_0,image_coord_src_1,image_coord_src_2,image_coord_dst_0,image_coord_dst_1,image_coord_dst_2,coord_src_0,coord_src_1,coord_src_2,coord_dst_0,coord_dst_1,coord_dst_2,branch_length,euclidean_distance,str_prop
0,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",mito,0,8,0,2009,1,3,1,1,343,199,4,293,131,0.396091,27.421821,15.909453,1.584364,23.424471,10.473057,14.571617,6.851657,0.470206
1,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",mito,1,1,2,136,1,3,1,1,389,134,2,386,129,0.396091,31.099383,10.712898,0.792182,30.859542,10.313163,0.797930,0.611719,0.766632
2,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",mito,2,2,3,236,1,3,1,1,490,346,2,483,338,0.396091,39.174030,27.661662,0.792182,38.614401,27.022086,1.217063,0.937619,0.770395
3,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",mito,3,3,7,339,1,3,1,2,139,220,3,134,213,0.792182,11.112633,17.588340,1.188273,10.712898,17.028711,1.734815,0.793638,0.457477
4,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",mito,4,27,9,12,1,1,0,2,141,229,2,144,231,0.792182,11.272527,18.307863,0.792182,11.512368,18.467757,0.306071,0.288253,0.941784
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9124,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",ER,9124,1,40011,40020,3,3,2,16,728,958,16,729,962,6.337456,58.201416,76.589226,6.337456,58.281363,76.909014,0.352903,0.329630,0.934052
9125,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",ER,9125,1,40013,40045,3,3,2,16,728,976,16,735,974,6.337456,58.201416,78.028272,6.337456,58.761045,77.868378,0.625859,0.582023,0.929958
9126,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",ER,9126,1,40020,40055,3,3,2,16,729,962,16,737,968,6.337456,58.281363,76.909014,6.337456,58.920939,77.388696,0.838267,0.799470,0.953718
9127,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",ER,9127,1,40045,40055,3,3,2,16,735,974,16,737,968,6.337456,58.761045,77.868378,6.337456,58.920939,77.388696,0.545912,0.505629,0.926210
9128,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",ER,9128,1,40045,40061,3,3,2,16,735,974,16,737,987,6.337456,58.761045,77.868378,6.337456,58.920939,78.907689,1.238002,1.051539,0.849384

Skeleton node table:

,image_name,mask_name,scale,object,point_id,node_type,connectivity,image_coord_0,image_coord_1,image_coord_2,coord_0,coord_1,coord_2,branch_ids,label
0,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",mito,0,Endpoint,1,1,343,199,0.396091,27.421821,15.909453,[0],8
1,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",mito,2,Endpoint,1,1,389,134,0.396091,31.099383,10.712898,[1],1
2,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",mito,3,Endpoint,1,1,490,346,0.396091,39.174030,27.661662,[2],2
3,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",mito,7,Endpoint,1,2,139,220,0.792182,11.112633,17.588340,[3],3
4,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",mito,9,Endpoint,1,2,141,229,0.792182,11.272527,18.307863,[4],27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8708,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",ER,40045,3-way,3,16,735,974,6.337456,58.761045,77.868378,"[9125, 9127, 9128]",1
8709,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",ER,40055,3-way,3,16,737,968,6.337456,58.920939,77.388696,"[8941, 9126, 9127]",1
8710,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",ER,40061,3-way,3,16,737,987,6.337456,58.920939,78.907689,"[9105, 9123, 9128]",1
8711,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",ER,40086,3-way,3,16,748,976,6.337456,59.800356,78.028272,"[8940, 9106, 9107]",1
8712,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",ER,40097,Endpoint,1,17,695,958,6.733547,55.563165,76.589226,[9114],1

The output here matches the output from the individual steps above: True
Skeleton images: True

The output here matches the output from the individual steps above for the branch table: True

The output here matches the output from the individual steps above for the node table: True

##### &#x1F453; **FYI:** This function has been added to `infer_subc.quantification.morphology` and can be imported with the following:
> ```python
> from infer_subc.quantification.morphology import get_org_morphology
> ```

In [19]:
from infer_subc.quantification.morphology import get_org_morphology

if include_skel and all_skel_tab:
    org_morph_tab_test, branch_tab_test, node_tab_test, skel_arrs = get_org_morphology(source_file_path = file_path,
                                     list_obj_names = org_file_names,
                                     list_obj_segs = organelles,
                                     list_intensity_img = intensities, 
                                     list_region_names = regions_file_names,
                                     list_region_segs = regions,
                                     mask_name=mask_name,
                                     scale=scale,
                                     include_skel=include_skel,
                                     all_skel_tab=all_skel_tab)
    print("Organelle morphology table:")
    display(org_morph_tab_test)
    print("Skeleton branch table:")
    display(branch_tab_test)
    print("Skeleton node table:")
    display(node_tab_test)
else:
    org_morph_tab_test, skel_arrs = get_org_morphology(source_file_path = file_path,
                                            list_obj_names = org_file_names,
                                            list_obj_segs = organelles,
                                            list_intensity_img = intensities, 
                                            list_region_names = regions_file_names,
                                            list_region_segs = regions,
                                            mask_name=mask_name,
                                            scale=scale,
                                            include_skel=include_skel,
                                            all_skel_tab=all_skel_tab)
    print("Organelle morphology table:")
    display(org_morph_tab_test)

# check is function output matches previous output
print(f"\nThe output here matches the output from the individual steps above: {org_morph_tab.equals(org_morph_tab_test)}")

if include_skel:
    print("Skeleton images:", all([np.array_equal(skel_arr_imgs[key], val) for key, val in skel_arrs.items()]))
    if all_skel_tab:
        print(f"\nThe output here matches the output from the individual steps above for the branch table: {branch_tab.equals(branch_tab_test)}")
        print(f"\nThe output here matches the output from the individual steps above for the node table: {node_tab.equals(node_tab_test)}")

Quantifying organelle morphology from 05052022_astro_control_2_Linear unmixing_0_cmle.ome.tiff
Warning(s) suppressed while quantifying mito. See 'method_morphology.ipynb' notebook for more details.
Warning(s) suppressed while quantifying golgi. See 'method_morphology.ipynb' notebook for more details.
Warning(s) suppressed while quantifying ER. See 'method_morphology.ipynb' notebook for more details.
Organelle morphology table:

Empty DataFrame
Columns: [image_name, mask_name, scale, object, label, centroid-0, centroid-1, centroid-2, bbox-0, bbox-1, bbox-2, bbox-3, bbox-4, bbox-5, volume, surface_area, SA_to_volume_ratio, equivalent_diameter, extent, euler_number, solidity, axis_major_length, min_intensity-mito-ch, min_intensity-golgi-ch, min_intensity-ER-ch, max_intensity-mito-ch, max_intensity-golgi-ch, max_intensity-ER-ch, mean_intensity-mito-ch, mean_intensity-golgi-ch, mean_intensity-ER-ch, standard_deviation_intensity-mito-ch, standard_deviation_intensity-golgi-ch, standard_deviation_intensity-ER-ch, cell_volume, skel_type, skel_type_num, skel_brh_count, skel_min_brh_length, skel_max_brh_length, skel_ave_brh_length, skel_sd_brh_length, skel_med_brh_length, skel_total_length, skel_brh_type_0_tot, skel_brh_type_1_tot, skel_brh_type_2_tot, skel_brh_type_3_tot, skel_comp_count, skel_node_count, skel_abs_punc_count, skel_ep_count, skel_jn_count, skel_ave_jn_deg, skel_max_deg, skel_mean_brh_str, skel_med_brh_str, skel_sd_brh_str, skel_width]
Index: []

Skeleton branch table:

,image_name,mask_name,scale,object,branch_id,label,point_id_src,point_id_dst,deg_src,deg_dst,branch_type,image_coord_src_0,image_coord_src_1,image_coord_src_2,image_coord_dst_0,image_coord_dst_1,image_coord_dst_2,coord_src_0,coord_src_1,coord_src_2,coord_dst_0,coord_dst_1,coord_dst_2,branch_length,euclidean_distance,str_prop
0,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",mito,0,8,0,2009,1,3,1,1,343,199,4,293,131,0.396091,27.421821,15.909453,1.584364,23.424471,10.473057,14.571617,6.851657,0.470206
1,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",mito,1,1,2,136,1,3,1,1,389,134,2,386,129,0.396091,31.099383,10.712898,0.792182,30.859542,10.313163,0.797930,0.611719,0.766632
2,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",mito,2,2,3,236,1,3,1,1,490,346,2,483,338,0.396091,39.174030,27.661662,0.792182,38.614401,27.022086,1.217063,0.937619,0.770395
3,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",mito,3,3,7,339,1,3,1,2,139,220,3,134,213,0.792182,11.112633,17.588340,1.188273,10.712898,17.028711,1.734815,0.793638,0.457477
4,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",mito,4,27,9,12,1,1,0,2,141,229,2,144,231,0.792182,11.272527,18.307863,0.792182,11.512368,18.467757,0.306071,0.288253,0.941784
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9124,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",ER,9124,1,40011,40020,3,3,2,16,728,958,16,729,962,6.337456,58.201416,76.589226,6.337456,58.281363,76.909014,0.352903,0.329630,0.934052
9125,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",ER,9125,1,40013,40045,3,3,2,16,728,976,16,735,974,6.337456,58.201416,78.028272,6.337456,58.761045,77.868378,0.625859,0.582023,0.929958
9126,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",ER,9126,1,40020,40055,3,3,2,16,729,962,16,737,968,6.337456,58.281363,76.909014,6.337456,58.920939,77.388696,0.838267,0.799470,0.953718
9127,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",ER,9127,1,40045,40055,3,3,2,16,735,974,16,737,968,6.337456,58.761045,77.868378,6.337456,58.920939,77.388696,0.545912,0.505629,0.926210
9128,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",ER,9128,1,40045,40061,3,3,2,16,735,974,16,737,987,6.337456,58.761045,77.868378,6.337456,58.920939,78.907689,1.238002,1.051539,0.849384

Skeleton node table:

,image_name,mask_name,scale,object,point_id,node_type,connectivity,image_coord_0,image_coord_1,image_coord_2,coord_0,coord_1,coord_2,branch_ids,label
0,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",mito,0,Endpoint,1,1,343,199,0.396091,27.421821,15.909453,[0],8
1,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",mito,2,Endpoint,1,1,389,134,0.396091,31.099383,10.712898,[1],1
2,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",mito,3,Endpoint,1,1,490,346,0.396091,39.174030,27.661662,[2],2
3,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",mito,7,Endpoint,1,2,139,220,0.792182,11.112633,17.588340,[3],3
4,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",mito,9,Endpoint,1,2,141,229,0.792182,11.272527,18.307863,[4],27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8708,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",ER,40045,3-way,3,16,735,974,6.337456,58.761045,77.868378,"[9125, 9127, 9128]",1
8709,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",ER,40055,3-way,3,16,737,968,6.337456,58.920939,77.388696,"[8941, 9126, 9127]",1
8710,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",ER,40061,3-way,3,16,737,987,6.337456,58.920939,78.907689,"[9105, 9123, 9128]",1
8711,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",ER,40086,3-way,3,16,748,976,6.337456,59.800356,78.028272,"[8940, 9106, 9107]",1
8712,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.396091, 0.079947, 0.079947)",ER,40097,Endpoint,1,17,695,958,6.733547,55.563165,76.589226,[9114],1

The output here matches the output from the individual steps above: True
Skeleton images: True

The output here matches the output from the individual steps above for the branch table: True

The output here matches the output from the individual steps above for the node table: True

-----
### 🧪 **Batch process *multiple images* from a <ins>SINGLE EXPERIMENT</ins>**

#### **`STEP 1` - Check the output file paths to see if quantification data already exists**

##### &#x1F6D1; &#x270D; **User Input Required:**

&#x1F453; **FYI:** The quantification pipeline outlined here will write new quantitative data to a csv file as each image is processed. This ensures that data is not lost if processing is inteRrupted. This step first checks if an output file of the same name already exists and lists any data included there. 

Specify the name of this dataset:
- `dataset_name`: A unique string identifier for this dataset. It will be included as metadata in output tables and as part of the output files names. It will be used to identify if any data has already been collected for this dataset.

In [ ]:
### USER INPUT REQUIRED ###
dataset_name = "test_dataset_1"

##### &#x1F3C3; **Run code; no user input required**

&#x1F453; **FYI:** This step defines the output csv file paths that will be created during interaction analysis batch processing below and checks if any data from this dataset already exists there. If so, the images that have quantitative data in each file will not be processed again. 

*Note: the `include_morpho`, `include_dist`, `include_additive_inter_imgs` variables defined above are used here to decide which tables should be looked for.*

In [ ]:
# define a function to check for existing data in csv files
def _load_existing_keys_csv(csv_path, key_cols, chunksize=250_000):
    keys = set()
    if not os.path.exists(csv_path):
        return keys
    for chunk in pd.read_csv(csv_path, usecols=key_cols, chunksize=chunksize):
        keys.update(map(tuple, chunk[key_cols].itertuples(index=False, name=None)))
    return keys


# specify the columns that will be checked per table
unique_keys = ['dataset', 'image_name']

# check if any existing data is present in outfiles
morpho_path = quant_data_path / f"{dataset_name}_org_morphology_metrics.csv"
existing_morpho_keys = _load_existing_keys_csv(morpho_path, unique_keys)

# show data that was found
if existing_morpho_keys:
    print(f"Found existing {dataset_name} data for {len(existing_morpho_keys)} images in {quant_data_path}. These images will be skipped during analysis to avoid duplicate data entries.")
else:
    print(f"No \"{dataset_name}\" data was found in {quant_data_path}. All images will be processed during analysis.")

Found existing test_dataset_1 data for 1 images in C:\Users\redre\Documents\CohenLab\scohen_lab_repo\infer-subc\sample_data\example_quant\quant. These images will be skipped during analysis to avoid duplicate data entries.

#### **`STEP 2` - List images and the segmentation file suffixes that should be collected for each**

##### &#x1F3C3; **Run code; no user input required**

&#x1F453; **FYI:** These steps collect a list of the images included in your "raw" (intensity image) data folder. Then, the masks suffixes and organelle suffixes are combined into one list.

In [ ]:
# reading list of files from the raw path
img_file_list = list_image_files(raw_data_path, raw_img_type)
print(f"Found {len(img_file_list)} images in {raw_data_path} for analysis:")
display(pd.DataFrame({"Image Name":img_file_list}))

# list of organelle segmentation and masks files to collect from each image
segs_to_collect = org_file_names + regions_file_names
print(f"The following segmentation files will be collected for each image: {segs_to_collect}")

Found 1 images in C:\Users\redre\Documents\CohenLab\scohen_lab_repo\infer-subc\sample_data\example_quant\raw for analysis:

                                                                                                                                            Image Name
0  C:\Users\redre\Documents\CohenLab\scohen_lab_repo\infer-subc\sample_data\example_quant\raw\05052022_astro_control_2_Linear unmixing_0_cmle.ome.tiff

The following segmentation files will be collected for each image: ['lyso', 'mito', 'golgi', 'perox', 'ER', 'LD', 'cell', 'nuc']

#### **`STEP 3` - Loop through the list of images and perform the morphology quantification on all organelles**

##### &#x1F6D1; &#x270D; **User Input Required:**

&#x1F453; **FYI:** This step loops through each image listed, reads the segmentation files, formats them appropriately, and then carries out morphology quantification via `get_org_morphology()`.

Specify if the quantification should be carried out with or without the scale:
- `use_scale`: True indicates that the function will use the scale metadata to produce "real world" metrics (e.g., microns, etc.). False will produce quantification results in pixel/voxel units.

*Note: the file path locations and file information provided in the beginning of the notebook will be used here for simplicity.*

In [ ]:
### USER INPUT REQUIRED ###
use_scale = True

##### &#x1F3C3; **Run code; no user input required**

&#x1F453; **FYI:** The block of code below loops through the list of files and runs the `get_org_morphology()` function on each one. The loop utilizes the following sequence of steps:
1) Find the paths for all of the organelle and mask segmentation files.
2) Collect the intensity channels and organelle segmentation files in the same order. Store them as lists.
3) Collect all of the region segmentation files in another list.
4) Determine the scale from the metadata if it is being used.
5) Run the get_org_morphology() function and add the resulting data table to the org_tab list.
6) Repeat the loop above for each image in the raw image list and add them sequentially to the org_tab list.

In [ ]:
# define function to append data to csv after each image is processed
def _append_atomic_csv(csv_path, df):
    if df.empty:
        return
    if not os.path.exists(csv_path):
        df.to_csv(csv_path, index=False)
        return
    existing = pd.read_csv(csv_path)
    merged = pd.concat([existing, df], axis=0, ignore_index=True)
    merged = merged.drop_duplicates()  # final guard against repeat values
    fd, tmp_path = tempfile.mkstemp(prefix='append_', suffix='.csv')
    os.close(fd)
    merged.to_csv(tmp_path, index=False)
    os.replace(tmp_path, csv_path)


# loop through list of images and quantify interaction metrics if data for that image do not already exist;
for img_f in img_file_list:
    # skip files that have already been processed
    if (dataset_name, img_f.stem) in existing_morpho_keys:
        print(f"Skipping {img_f.name} as it is already listed in the output file(s).")
        continue

    # process analysis for this cells
    else:
        filez = find_segmentation_tiff_files(img_f, segs_to_collect, seg_data_path, suffix_separator)

        # read in raw file and metadata
        img_data, meta_dict = read_czi_image(filez["raw"])

        # create intensities from raw file as list based on the channel order provided
        if channel_axis != 0:
            img_data = np.moveaxis(img_data, channel_axis, 0)
        intensities = [img_data[ch] for ch in org_channels_ordered]

        # store organelle images as list
        organelles = [read_tiff_image(filez[org]) for org in org_file_names]

        # load regions as a list based on order in list (should match order in "masks" file)
        regions = [read_tiff_image(filez[r]) for r in regions_file_names] 

        # define the scale
        if use_scale is True:
            scale_tup = meta_dict['scale']
        else:
            scale_tup = None

        if include_skel and all_skel_tab:
            org_metrics, branch_table, node_table, skel_arr_dict = _get_org_morphology(source_file_path=img_f,
                                         list_obj_names=org_file_names,
                                         list_obj_segs=organelles,
                                         list_intensity_img=intensities, 
                                         list_region_names=regions_file_names,
                                         list_region_segs=regions, 
                                         mask_name=mask_name,
                                         scale=scale_tup,
                                         include_skel=include_skel,
                                         all_skel_tab=all_skel_tab)
            # save the morphology (or labels only) table data per image directly to csv
            org_metrics.insert(loc=0,column='dataset',value=dataset_name)
            _append_atomic_csv(morpho_path, org_metrics)
            del org_metrics  # free up memory

            # save branch and node tables if skeletonization is included
            branch_path = quant_data_path / f"{dataset_name}_skeleton_branch_data.csv"
            node_path = quant_data_path / f"{dataset_name}_skeleton_node_data.csv"
            _append_atomic_csv(branch_path, branch_table)
            _append_atomic_csv(node_path, node_table)
            del branch_table, node_table  # free up memory
        org_metrics, skel_arr_dict = _get_org_morphology(source_file_path=img_f,
                                         list_obj_names=org_file_names,
                                         list_obj_segs=organelles,
                                         list_intensity_img=intensities, 
                                         list_region_names=regions_file_names,
                                         list_region_segs=regions, 
                                         mask_name=mask_name,
                                         scale=scale_tup,
                                         include_skel=include_skel)
        
        # save the morphology (or labels only) table data per image directly to csv
        org_metrics.insert(loc=0,column='dataset',value=dataset_name)
        _append_atomic_csv(morpho_path, org_metrics)
        del org_metrics  # free up memory

    if include_skel:
             # save the skeleton images
            for skel_name, skel_img in skel_arr_dict.items():
                if skel_img is not None:
                    if not (Path(img_f)/f"{meta_dict['file_name'].stem}-{skel_name}-skeleton.tiff").exists():
                        export_inferred_organelle(skel_img, f"{skel_name}-skeleton", meta_dict, img_f)
                    else:
                        warnings.warn(f"Some of the skeleton images already exist for {meta_dict['file_name'].stem} in {img_f}. They will not be overwritten.", UserWarning)
            del skel_arr_dict  # free up memory

Skipping 05052022_astro_control_2_Linear unmixing_0_cmle.ome.tiff as it is already listed in the output file(s).

#### **`DEFINE` - The batch_process_org_morph() function**

The following code combines the steps above into a single function that can be accessed as part of the `infer-subc` package. The function takes in file path information for intensity and segmentation images and the parameters necessary to quantify organelle morphology metrics. 

This function can be utilized from infer-subc using:
```python
infer_subc.quantification.interactions.batch_process_org_morph()
```

#### &#x1F3C3; **Run code; no user input required**

&#x1F453; **FYI:** This code block defines a prototypes of the `batch_process_org_morph()` function based on the steps above and tests it below.

!!!ALSO ADD OPTION TO OUTPUT BRANCH AND NODE TABLES

In [ ]:
def _batch_process_org_morph(dataset_name: str,
                             raw_path: Union[Path,str], 
                             seg_path: Union[Path,str],
                             quant_path: Union[Path, str], 
                             raw_file_type: str,
                             channel_axis: int,
                             organelle_names: List[str],
                             organelle_channels: Union[List[int], None]=None,
                             region_names: Union[List[str], None]=None,
                             mask_name: Union[str, None]=None,
                             use_scale:bool=True,
                             include_skel: Union[List[str], None] = [],
                             all_skel_tab: bool = False,
                             seg_suffix:Union[str, None]=None):
    """ 
    batch process segmentation quantification (morphology, distribution, contacts); this function is currently optimized to process images from one file folder per image type (e.g., raw, segmentation)
    the output csv files are saved to the indicated quant_path folder

    Parameters:
    ----------
    dataset_name : str
        A unique string identifier for the dataset being processed. It will be included as metadata in output tables and as 
        part of the output files names. It will be used to identify if any data has already been collected for this dataset.
    raw_path: Union[Path,str]
        Path or str to the folder that contains the raw image files
    seg_path: Union[Path,str]
        Path or str to the folder that contains the segmentation tiff files
    quant_path: Union[Path, str]
        Path or str to the folder that the output datatables will be saved to
    raw_file_type: str
        File type of the raw images (e.g., "czi", "tiff")
    channel_axis : int
        Axis corresponding to the channels in the image data
    organelle_names: List[str]
        List of organelle names to analyze. These names should match the suffix on the organelle segmentation files
    organelle_channels: Union[List[int], None]=None
        List of intensity channel indices in the raw files corresponding to each organelle included in organelle_names.
        The order should match organelle_names. 
        If no intensity analysis is to be included, specify None here.
    region_names: Union[List[str], None]=None
        List of region names to analyze. Usually ['cell', 'nuc'] for cell mask and nucleus.
        If no regions are to be included, specify None here.
    mask_name: Union[str, None]=None
        Name of the region to use for segmentation (if any). This name should be included in the regions_name variable.
        If None, the entire image will be quantified.
    use_scale: bool=True
        Whether to apply scaling to the quantitative data; scaled data will be in real world units (e.g., microns) rather than pixels/voxels
    include_skel: Union[List[str], None]
        List of 3D organelle segmentation arrays to be skeletonized in addition to morphology metrics.
    all_skel_tab: bool
        Whether to output all skeleton tables (True) or just the skeleton metrics table (False).
        The names should match those included in list_obj_names. If no skeletonization is to be included, specify [] (empty list).
    seg_suffix:Union[str, None]=None
        Any additional text that is included in the segmentation tiff files between the file stem and the segmentation suffix, not including the initial "-"

    Returns:
    ----------
    None: files are saved to quant_path directly
    """
    
    start = time.time()
    count = 0

    # create path objects if inputs are strings
    if isinstance(raw_path, str): raw_path = Path(raw_path)
    if isinstance(seg_path, str): seg_path = Path(seg_path)
    if isinstance(quant_path, str): quant_path = Path(quant_path)
    
    # create directory is it doesn't exist
    if not Path.exists(quant_path):
        Path.mkdir(quant_path)
        print(f"Output file path not found. Making {quant_path}.")

    # check if any existing data is present in outfiles to skip already processed images
    unique_keys = ['dataset', 'image_name']

    morpho_path = quant_path / f"{dataset_name}_org_morphology_metrics.csv"
    existing_morpho_keys = _load_existing_keys_csv(morpho_path, unique_keys)

    # reading list of files from the raw path
    img_file_list = list_image_files(raw_path, raw_file_type)
    len_file_list = len(img_file_list)

    # list of organelle segmentation and masks files to collect from each image
    segs_to_collect = organelle_names + region_names if region_names is not None else organelle_names

    # loop through list of cell analyzing each and appending the data to the empty list
    for img_f in img_file_list:
        img_start = time.time()
        count = count + 1
        # skip files that have already been processed
        if (dataset_name, img_f.stem) in existing_morpho_keys:
            print(f"Skipping {img_f.name} as it is already listed in the output file(s).")
            continue
        # process analysis for this cells
        else:
            filez = find_segmentation_tiff_files(img_f, segs_to_collect, seg_path, seg_suffix)

            # read in raw file and metadata
            img_data, meta_dict = read_czi_image(filez["raw"])

            # create intensities from raw file as list based on the channel order provided
            if organelle_channels is None:
                intensities = None
                print("No intensity channel information provided.")
            else:
                if channel_axis != 0:
                    img_data = np.moveaxis(img_data, channel_axis, 0)
                intensities = [img_data[ch] for ch in organelle_channels]

            # store organelle images as list
            organelles = [read_tiff_image(filez[org]) for org in organelle_names]

            # load regions as a list based on order in list (should match order in "masks" file)
            if region_names is None:
                regions = None
            else:
                regions = [read_tiff_image(filez[r]) for r in region_names] 

            # define the scale
            if use_scale is True:
                scale = meta_dict['scale']
            else:
                scale = None
            if include_skel and all_skel_tab:
                org_metrics, branch_table, node_table, skel_arr_dict = _get_org_morphology(source_file_path=img_f,
                                                    list_obj_names=organelle_names,
                                                    list_obj_segs=organelles,
                                                    list_intensity_img=intensities,
                                                    list_region_names=region_names,
                                                    list_region_segs=regions,
                                                    mask_name=mask_name,
                                                    scale=scale,
                                                    include_skel=include_skel,
                                                    all_skel_tab=all_skel_tab)
                # save the morphology (or labels only) table data per image directly to csv
                org_metrics.insert(loc=0,column='dataset',value=dataset_name)
                _append_atomic_csv(morpho_path, org_metrics)
                del org_metrics  # free up memory

                # save branch and node tables if skeletonization is included
                branch_path = quant_path / f"{dataset_name}_skeleton_branch_data.csv"
                node_path = quant_path / f"{dataset_name}_skeleton_node_data.csv"
                _append_atomic_csv(branch_path, branch_table)
                _append_atomic_csv(node_path, node_table)
                del branch_table, node_table  # free up memory

                org_metrics, skel_arr_dict = _get_org_morphology(source_file_path=img_f,
                                                    list_obj_names=organelle_names,
                                                    list_obj_segs=organelles,
                                                    list_intensity_img=intensities, 
                                                    list_region_names=region_names,
                                                    list_region_segs=regions, 
                                                    mask_name=mask_name,
                                                    scale=scale,
                                                    include_skel=include_skel)

                # save the morphology table data per image directly to csv
                org_metrics.insert(loc=0,column='dataset',value=dataset_name)
                _append_atomic_csv(morpho_path, org_metrics)
                del org_metrics  # free up memory

            if include_skel:
             # save the skeleton images
                for skel_name, skel_img in skel_arr_dict.items():
                    if skel_img is not None:
                        if not (Path(img_f)/f"{meta_dict['file_name'].stem}-{skel_name}-skeleton.tiff").exists():
                            export_inferred_organelle(skel_img, f"{skel_name}-skeleton", meta_dict, img_f)
                        else:
                            warnings.warn(f"Some of the skeleton images already exist for {meta_dict['file_name'].stem} in {img_f}. They will not be overwritten.", UserWarning)
                del skel_arr_dict  # free up memory
                
            end2 = time.time()
            print(f"Completed quantification of {meta_dict['file_name']} in {(end2-img_start)/60} mins.")
            print(f"{count}/{len_file_list} images have been processed.")
            print(f"Time elapsed: {(end2-img_start)/60} mins")

    end = time.time()
    print(f"Quantification for {count} files is COMPLETE! Files saved to '{quant_path}'.")
    print(f"It took {(end - start)/60} minutes to quantify these files.")

#### &#x1F3C3; **Run code; no user input required**

&#x1F453; **FYI:** This code block applies the function above to your test image. The settings specified above are applied here.

In [ ]:
# define a new dataset name for comparison
dataset_name2 = "test_dataset_1-comparison"

_batch_process_org_morph(dataset_name=dataset_name2,
                        seg_path = seg_data_path,
                        quant_path = quant_data_path, 
                        raw_path = raw_data_path, 
                        raw_file_type = raw_img_type,
                        channel_axis = channel_axis,
                        organelle_names = org_file_names,
                        organelle_channels = org_channels_ordered,
                        region_names = regions_file_names,
                        mask_name = mask_name,
                        use_scale = use_scale,
                        include_skel = include_skel,
                        seg_suffix = suffix_separator)

# compare the output files from both dataset runs to ensure they are identical
morpho_file1 = quant_data_path / f"{dataset_name}_org_morphology_metrics.csv"
morpho_file2 = quant_data_path / f"{dataset_name2}_org_morphology_metrics.csv"
branch_file1 = quant_data_path / f"{dataset_name}_skeleton_branch_data.csv"
branch_file2 = quant_data_path / f"{dataset_name2}_skeleton_branch_data.csv"
node_file1 = quant_data_path / f"{dataset_name}_skeleton_node_data.csv"
node_file2 = quant_data_path / f"{dataset_name2}_skeleton_node_data.csv"

# determine if files are identical except for the dataset name column
if morpho_file1.exists() and morpho_file2.exists():
    morph_1 = pd.read_csv(morpho_file1)
    morph_2 = pd.read_csv(morpho_file2)
    morph_2['dataset'] = morph_1['dataset']  # set dataset names to be the same for comparison
    print("\nMorphology metrics files identical:", morph_1.equals(morph_2))
if branch_file1.exists() and branch_file2.exists():
    branch_1 = pd.read_csv(branch_file1)
    branch_2 = pd.read_csv(branch_file2)
    branch_2['dataset'] = branch_1['dataset']  # set dataset names to be the same for comparison
    print("Skeleton branch data files identical:", branch_1.equals(branch_2))
if node_file1.exists() and node_file2.exists():
    node_1 = pd.read_csv(node_file1)
    node_2 = pd.read_csv(node_file2)
    node_2['dataset'] = node_1['dataset']  # set dataset names to be the same for comparison
    print("Skeleton node data files identical:", node_1.equals(node_2))

Skipping 05052022_astro_control_2_Linear unmixing_0_cmle.ome.tiff as it is already listed in the output file(s).
Quantification for 1 files is COMPLETE! Files saved to 'C:\Users\redre\Documents\CohenLab\scohen_lab_repo\infer-subc\sample_data\example_quant\quant'.
It took 0.0010456085205078126 minutes to quantify these files.

Morphology metrics files identical: True

##### &#x1F453; **FYI:** This function has been added to `infer_subc.quantification.morphology` and can be imported with the following:
> ```python
> from infer_subc.quantification.morphology import batch_process_org_morph
> ```

In [ ]:
from infer_subc.quantification.morphology import batch_process_org_morph

# define a new dataset name for comparison
dataset_name3 = "test_dataset_1-testcomparison"

batch_process_org_morph(dataset_name=dataset_name3,
                        seg_path = seg_data_path,
                        quant_path = quant_data_path, 
                        raw_path = raw_data_path, 
                        raw_file_type = raw_img_type,
                        channel_axis=channel_axis,
                        organelle_names = org_file_names,
                        organelle_channels = org_channels_ordered,
                        region_names = regions_file_names,
                        mask_name = mask_name,
                        use_scale = use_scale,
                        seg_suffix = suffix_separator,
                        include_skel = include_skel)

# compare the output files from both dataset runs to ensure they are identical
morpho_file3 = quant_data_path / f"{dataset_name3}_org_morphology_metrics.csv"
branch_file3 = quant_data_path / f"{dataset_name3}_skeleton_branch_data.csv"
node_file3 = quant_data_path / f"{dataset_name3}_skeleton_node_data.csv"

# determine if files are identical except for the dataset name column
if morpho_file1.exists() and morpho_file3.exists():
    morph_1 = pd.read_csv(morpho_file1)
    morph_3 = pd.read_csv(morpho_file3)
    morph_3['dataset'] = morph_1['dataset']  # set dataset names to be the same for comparison
    print("\nMorphology metrics files identical:", morph_1.equals(morph_3))
if branch_file1.exists() and branch_file3.exists():
    branch_1 = pd.read_csv(branch_file1)
    branch_3 = pd.read_csv(branch_file3)
    branch_3['dataset'] = branch_1['dataset']  # set dataset names to be the same for comparison
    print("Skeleton branch data files identical:", branch_1.equals(branch_3))
if node_file1.exists() and node_file3.exists():
    node_1 = pd.read_csv(node_file1)
    node_3 = pd.read_csv(node_file3)
    node_3['dataset'] = node_1['dataset']  # set dataset names to be the same for comparison
    print("Skeleton node data files identical:", node_1.equals(node_3))

Skipping 05052022_astro_control_2_Linear unmixing_0_cmle.ome.tiff as it is already listed in the output file(s).
Quantification for 1 files is COMPLETE! Files saved to 'C:\Users\redre\Documents\CohenLab\scohen_lab_repo\infer-subc\sample_data\example_quant\quant'.
It took 0.0007083853085835775 minutes to quantify these files.

Morphology metrics files identical: True

-----
### 🧮 **Summarize metrics *per image/mask* across <INS>ONE OR MORE EXPERIMENTS</ins>**

#### **`STEP 1` - Get the orgnaelle morphology .csv files**

#### &#x1F6D1; &#x270D; **User Input Required:**

&#x1F453; **FYI:** Here, the data output from batch_process_org_morph() from one or more datasets is combined before summarization.

Please specify the list file paths to include in this analysis:
- `csv_path_list`: a list of file paths that include the output csv files from batch_process_org_morph() for one or more datasets. If there is more than one dataset in each location, they will all be read in here as long as each dataset has a unique name (as specified the by dataset_name variable).

In [ ]:
### USER INPUT REQUIRED ###
csv_path_list = [quant_data_path]

##### &#x1F3C3; **Run code; no user input required**

&#x1F453; **FYI:** These steps collect all of the organelle interactions .csv quantification files from the list of locations and combines them so that there is now one data table per analysis type included.

Here, we will just use the single data path specified as quant_data_path earlier in the notebook, but multiple paths can be specified is desired. This path will have a few datasets in it if the above was run through fully.

In [ ]:
###################
# Read in the csv files and combine them into one of each type
###################
# create empty list to hold the morphology tables from different experiments
org_tabs = []

# loop through all of the locations listed above and find the _org_morph files; append them to the list above
for loc in csv_path_list:

    # list all csv files in the location
    files_store = sorted(loc.glob("*.csv"))

    # find the unique datasets in this location based on the prefixes before "_org_morphology_metrics"
    prefixes = set(f.name.split("_org_morphology_metrics")[0] for f in files_store if "_org_morphology_metrics" in f.name)
    print(f"Found the following datasets in {loc}:", prefixes)
    for prefix in prefixes:
        # select only the files from this dataset
        files_subset = [f for f in files_store if f.name.startswith(prefix +"_org_morphology_metrics")]
        for file in files_subset:
            stem = file.stem
            if "_org_morph" in stem:
                test_orgs = pd.read_csv(file, index_col=0)
                org_tabs.append(test_orgs)

# combine the org_morph lists found above into one table
org_df = pd.concat(org_tabs,axis=0, join='outer').reset_index()

print("Morphology metrics from all datasets:")
org_df.head(10)

Found the following datasets in C:\Users\redre\Documents\CohenLab\scohen_lab_repo\infer-subc\sample_data\example_quant\quant: {'test_dataset_1-testcomparison', 'test_dataset_1-comparison', 'test_dataset_1'}
Morphology metrics from all datasets:

,dataset,image_name,mask_name,scale,object,label,centroid-0,centroid-1,centroid-2,bbox-0,bbox-1,bbox-2,bbox-3,bbox-4,bbox-5,volume,surface_area,SA_to_volume_ratio,equivalent_diameter,extent,euler_number,solidity,axis_major_length,min_intensity-lyso-ch,min_intensity-mito-ch,min_intensity-golgi-ch,min_intensity-perox-ch,min_intensity-ER-ch,min_intensity-LD-ch,max_intensity-lyso-ch,max_intensity-mito-ch,max_intensity-golgi-ch,max_intensity-perox-ch,max_intensity-ER-ch,max_intensity-LD-ch,mean_intensity-lyso-ch,mean_intensity-mito-ch,mean_intensity-golgi-ch,mean_intensity-perox-ch,mean_intensity-ER-ch,mean_intensity-LD-ch,standard_deviation_intensity-lyso-ch,standard_deviation_intensity-mito-ch,standard_deviation_intensity-golgi-ch,standard_deviation_intensity-perox-ch,standard_deviation_intensity-ER-ch,standard_deviation_intensity-LD-ch,cell_volume,skel_type,skel_type_num,skel_brh_count,skel_branch_ids,skel_min_brh_length,skel_max_brh_length,skel_ave_brh_length,skel_sd_brh_length,skel_med_brh_length,skel_total_length,skel_brh_type_0_tot,skel_brh_type_0_id,skel_brh_type_1_tot,skel_brh_type_1_ids,skel_brh_type_2_tot,skel_brh_type_2_ids,skel_brh_type_3_tot,skel_brh_type_3_ids,skel_comp_count,skel_node_count,skel_abs_punc_count,skel_ep_count,skel_jn_count,skel_ave_jn_deg,skel_max_deg,skel_point_ids,skel_mean_brh_str,skel_med_brh_str,skel_sd_brh_str,skel_width
0,test_dataset_1-testcomparison,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.3961, 0.0799, 0.0799)",lyso,8,1.141775,22.711552,25.772132,2,277,316,6,292,330,0.582274,6.743121,11.580673,1.036039,0.273810,1,0.647887,1.614884,1285.616333,94.128250,19.917885,369.165741,7.748461,0.020725,16779.892578,2804.360840,10900.666016,2305.010498,15278.381836,425.010254,5104.099609,886.269714,1683.677124,1007.581299,4343.315918,74.037712,3564.181396,564.342834,2117.183594,396.034515,2920.478271,85.008774,3989.313888,Rod,1,1,[29],1.613309,1.613309,1.613309,0.000000,1.613309,1.613309,1,[29],0,[],0,[],0,[],1,2,0,2,0,NaN,2,[ 131 132 134 138 141 144 846 1730 1732 1733 1734],0.720139,0.720139,0.000000,0.043607
1,test_dataset_1-testcomparison,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.3961, 0.0799, 0.0799)",lyso,9,0.912476,24.476070,7.679057,1,291,83,5,326,110,1.367077,16.097858,11.775382,1.376992,0.142857,0,0.426204,3.369081,1013.153076,83.833046,2.192753,35.756939,8.423473,0.457328,10297.416992,1530.896240,1848.742188,3966.382324,16039.733398,601.457703,3239.871582,542.845947,240.935944,1120.918823,5423.116211,95.298370,1329.609131,262.423401,265.724274,615.322571,3791.130615,117.376251,3989.313888,Network,3,6,"[36, 37, 39, 40, 41, 43]",0.159894,2.156216,0.950518,0.653200,0.841514,5.703105,0,[],3,"[36, 37, 43]",3,"[39, 40, 41]",0,[],1,6,0,3,3,3.0,3,[157 158 159 160 161 162 163 164 165 166 167 169 171 172 173 176 177 181\n 182 191 193 194 195 197 198 200 201 202 205 206 208 209 211 212 214 215\n 217 218 221 222 223 224 225 226 227 228 229 230 231 232 233 234 238 910\n 913 916],0.812364,0.925079,0.212091,0.008566
2,test_dataset_1-testcomparison,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.3961, 0.0799, 0.0799)",lyso,10,0.847025,24.389165,14.379800,1,300,168,4,312,191,0.493667,6.656172,13.483126,0.980570,0.235507,1,0.592705,1.971751,2126.777832,105.011932,1.456444,281.090118,174.789825,1.535896,5353.251953,1124.640503,744.592712,1594.871338,14765.541992,129.332352,2964.641113,476.833374,195.540482,816.901062,4241.692871,23.083330,837.988831,184.350601,173.338791,294.342834,2975.732910,22.959909,3989.313888,Rod,1,1,[0],1.776692,1.776692,1.776692,0.000000,1.776692,1.776692,1,[0],0,[],0,[],0,[],1,2,0,2,0,NaN,2,[ 0 1 2 3 168 170 174 178 179 183 184 185 186 187 188 189 192],0.800587,0.800587,0.000000,0.000000
3,test_dataset_1-testcomparison,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.3961, 0.0799, 0.0799)",lyso,11,0.396091,26.723617,7.978711,1,333,98,2,337,103,0.037974,1.077901,28.384960,0.417027,0.750000,1,inf,0.518173,2168.356201,138.892502,0.765295,66.503960,21.599552,0.277797,2519.051025,385.233704,4.410619,323.145721,483.372253,8.012388,2328.289062,225.411758,2.321094,188.403519,197.549667,2.956841,113.692070,73.951630,1.107617,84.264969,142.647247,2.437857,3989.313888,Rod,1,1,[1],0.272956,0.272956,0.272956,0.000000,0.272956,0.272956,1,[1],0,[],0,[],0,[],1,2,0,2,0,NaN,2,[4 5 6 7],0.926210,0.926210,0.000000,0.000000
4,test_dataset_1-testcomparison,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.3961, 0.0799, 0.0799)",lyso,12,0.803499,26.978034,9.320841,1,329,111,4,346,126,0.620248,7.905151,12.745145,1.058089,0.320261,1,0.554299,1.858534,1226.483521,86.760468,8.114938,173.781754,79.932518,0.143019,9552.619141,2360.065186,929.692322,3206.732666,13272.247070,595.857422,3462.730713,565.118774,323.051788,926.241821,4061.333496,72.372307,1514.089233,361.964233,245.055542,539.632690,3539.107910,114.294785,3989.313888,Rod,1,1,[2],1.696745,1.696745,1.696745,0.000000,1.696745,1.696745,1,[2],0,[],0,[],0,[],1,2,0,2,0,NaN,2,[ 8 9 10 11 12 13 14 15 246 247 248 251 255 257 258 259],0.620716,0.620716,0.000000,0.009993
5,test_dataset_1-testcomparison,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.3961, 0.0799, 0.0799)",lyso,13,0.938736,28.536282,24.764383,2,353,306,4,362,315,0.253162,3.223299,12.732134,0.784875,0.617284,1,0.900901,0.855601,2128.789307,244.583923,9.177627,172.702606,476.548218,3.923572,8291.632812,1547.103149,434.864960,1461.260864,9213.311523,409.318573,3929.179932,652.714783,117.807236,673.068359,2657.095947,55.380138,1548.771973,286.682678,105.116791,340.393829,2136.340332,79.985191,3989.313888,Punctate,0,0,[],NaN,NaN,NaN,NaN,NaN,0.000000,0,[],0,[],0,[],0,[],1,1,1,0,0,NaN,0,[262],NaN,NaN,NaN,0.159894
6,test_dataset_1-testcomparison,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.3961, 0.0799, 0.0799)",lyso,14,0.882203,30.494057,9.613536,1,354,109,4,412,134,2.227830,26.756873,12.010286,1.620421,0.202299,0,0.356131,5.794626,1211.699585,118.806526,3.029471,44.667004,0.025324,0.037494,9403.426758,15267.514648,3763.956055,9268.221680,21087.123047,1031.801147,3426.729004,1295.166748,597.481812,813.382751,4000.325684,109.140495,1402.662231,1899.740845,599.776611,765.896545,3779.862305,182.580933,3989.313888,Network,3,6,"[52, 53, 54, 56, 57, 58]",0.512797,4.637174,1.695304,1.389717,1.324037,10.171825,0,[],3,"[52, 56, 58]",3,"[53, 54, 57]",0,[],1,6,0,3,3,3.0,3,[ 16 17 18 19 20 21 22 264 266 268 269 272 274 276\n 277 278 279 280 282 283 284 285 287 288 290 291 293 294\n 296 297 299 300 302 303 304 305 307 308 309 310 312 313\n 314 316 317 318 319 320 321 323 324 329 330 332 333 334\n 335 337 339 343 344 346 347 348 349 351 355 371 375 376\n 378 380 381 382 384 386 387 391 392 395 953 956 958 1037\n 1040 1044 1048 1051 1054 1057],0.742065,0.750617,0.170960,0.005330
7,test_dataset_1-testcomparison,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.3961, 0.0799, 0.0799)",lyso,15,1.123908,29.275092,34.440168,2,359,425,6,373,437,0.405060,5.343589,13.192094,0.917995,0.238095,1,0.698690,1.838659,652.921631,215.307770,51.270817,151.102158,729.971436,1.946125,10435.677734,2221.004639,2227.846924,2157.682861,11697.901367,455.607758,4239.603516,855.013489,660.474365,750.466797,4036.326660,95.185715,2103.884033,431.237854,530.332458,517.099426,2588.983643,107.694237,3989.313888,Rod,1,1,[51],1.024054,1.024054,1.024054,0.000000,1.024054,1.024054,1,[51],0,[],0,[],0,[],1,2,0,2,0,NaN,2,[273 275 281 286 966 967 973 974],0.767091,0.767091,0.000000,0.119920
8,test_dataset_1-testcomparison,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.3961, 0.0799, 0.0799)",lyso,16,1.116463,30.373910,28.505530,2,373,344,5,391,371,1.326571,10.746874,8.101241,1.363256,0.359396,1,0.771723,2.481988,1700.015991,98.587387,15.361661,133.569473,168.800095,0.106369,17164.935547,12752.250000,8357.171875,2855.031006,23811.451172,488.808807,5311.704590,1081.739136,1002.723022,836.046936,3672.690674,75.628685,3214.283203,1400.086060,1440.943726,545.020691,4032.200928,101.001892,3989.313888,Rod,1,1,[60],1.343842,1.343842,1.343842,0.000000,1.343842,1.343842,1,[60],0,[],0,[],0,[],1,2,0,2,0,NaN,2,[336 338 340 341 342 983 987 988 990 991 992 993],0.776918,0.776918,0.000000,0.242863
9,test_dataset_1-testcomparison,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.3961, 0.0799, 0.0799)",lyso,17,1.037859,31.915551,18.358462,1,395,223,5,404,238,0.399997,4.883410,12.208627,0.914154,0.292593,1,0.721461,1.294541,1161.524780,177.582520,4.049506,336.062653,82.602867,25.942051,7702.685059,1125.977417,1124.020264,3580.164795,32151.119141,1119.214600,3647.437988,430.895874,210.316605,1184.926025,11239.267578,356.090912,1406.781616,183.475815,232.301178,616.592834,9823.014648,202.985870,3989.313888,Rod,1,1,[67],0.684868,0.684868,0.684868,0.000000,0.684868,0.684868,1,[67],0,[],0,[],0,[],1,2,0,2,0,NaN,2,[ 370 372 373 374 1062],0.779114,0.779114,0.000000,0.063958

#### **`STEP 2` - Summarize the mean, median, and standard deviation of each metric per image/mask region**

##### &#x1F3C3; **Run code; no user input required**

&#x1F453; **FYI:** The block of code below summarizes the metrics per image/mask. The following are summarized:
- The number, total volume, volume fraction (total org vol/mask volume), and total surface area of each organelle per image/mask
- The mean, median and standard deviation of the "SA_to_volume_ratio", "equivalent_diameter", "extent", "euler_number", "solidity", and "axis_major_length" metrics for each organelle per image/mask

In [ ]:
###################
# summary stat group
###################
group_by = ['dataset', 'image_name', 'mask_name', 'scale', 'object']
sharedcolumns = ["SA_to_volume_ratio", "equivalent_diameter", "extent", "euler_number", "solidity", "axis_major_length"]
# add skeleton metrics to the shared columns if they are included in the data
if include_skel:
    skel_cols = ["skel_total_length",
                 "skel_abs_punc_count",
                 "skel_ep_count",
                 "skel_jn_count",
                 "skel_node_count",
                 "skel_brh_count"]
    skel_cols_2 = ["skel_brh_type_0_tot",
                         "skel_brh_type_1_tot",
                           "skel_brh_type_2_tot",
                             "skel_brh_type_3_tot",
                        "skel_comp_count",
                        "skel_ave_jn_deg",
                        "skel_max_deg",
                        "skel_mean_brh_str",
                        "skel_width"]
ag_func_standard = ['mean', 'median', 'std']

###################
# summarize shared measurements between org_df and contacts_df
###################
tab1 = org_df[group_by + ['label']].groupby(group_by).agg(['count'])
tab1.rename(columns={'label': 'org'}, inplace=True)
tab2 = org_df[group_by + ['volume', 'surface_area']].groupby(group_by).agg(['sum'] + ag_func_standard)
tab3 = org_df[group_by + sharedcolumns].groupby(group_by).agg(ag_func_standard)
org_summary = pd.merge(tab1, tab2, 'outer', on=group_by)
org_summary = pd.merge(org_summary, tab3, 'outer', on=group_by)
if include_skel:
    tab4 = org_df[group_by + skel_cols].groupby(group_by).agg(['sum'] + ag_func_standard)
    tab5 = org_df[group_by + skel_cols_2].groupby(group_by).agg(ag_func_standard)
    org_summary = pd.merge(org_summary, tab4, 'outer', on=group_by)
    org_summary = pd.merge(org_summary, tab5, 'outer', on=group_by)

# Get mask_name and corresponding volume column per group & calculate volume fraction
mask_names = org_df.groupby(group_by)['mask_name'].first()
mask_volume_data = org_df.groupby(group_by).first().apply(lambda row: row[f"{mask_names.loc[row.name]}_volume"], axis=1)
org_summary.insert(org_summary.columns.get_loc(('volume', 'sum')) + 1, ('volume', 'fraction'), org_summary[('volume', 'sum')]/mask_volume_data)

###################
# additional skeleton summarization inspired by mitograph measurments (if skeletonization is included)
###################


# This will be replaced with an actual checker in the function
if include_skel:
    # a temporary table used to calculate the average node degree, fusion score, fission score, connectivity, and heterogeneity for each organelle per cell
    # these measurements are inspired by the mitograph quantification metrics, but adapted to be more generalizable to different organelles
    skel_ff = org_df.assign(sum_jnxdeg = lambda x: x['skel_ave_jn_deg'] * x['skel_jn_count'],
                            is_punc = lambda df: (df['skel_type'] == "Punctate").astype(int),
                            is_rod = lambda df: (df['skel_type'] == "Rod").astype(int),
                            is_iso_cycle = lambda df: (df['skel_type'] == "Isolated Cycle").astype(int),
                            is_network = lambda df: (df['skel_type'] == "Network").astype(int)).groupby(group_by).agg({
        'label': 'count',
        'volume': ['mean','std'],
        'skel_total_length': ['max','sum','mean','std'],
        'skel_brh_count': ['sum','mean','std'],
        'skel_abs_punc_count': ['sum'],
        'skel_ep_count': 'sum',
        'skel_jn_count': ['sum'],
        'skel_node_count': ['sum','mean','std'],
        'sum_jnxdeg': 'sum',
        'skel_width': ['mean','std'],
        'is_punc': 'sum',
        'is_rod': 'sum',
        'is_iso_cycle': 'sum',
        'is_network': 'sum'
    }).assign(
        punctate_count = lambda df: df['is_punc'],
        rod_count = lambda df: df['is_rod'],
        iso_cycle_count = lambda df: df['is_iso_cycle'],
        network_count = lambda df: df['is_network'],
        skel_avg_node_deg = lambda df: (df['sum_jnxdeg','sum'] + df['skel_ep_count','sum']) / df['skel_node_count','sum'],
        skel_fusion_score = lambda df: (df['skel_total_length','max']/df['skel_total_length','sum']) + 
            (df['skel_total_length','sum']/df['skel_brh_count','sum']) + df['skel_avg_node_deg'],
        skel_fission_score = lambda df: (df['label','count']/df['skel_total_length','sum']) + 
            (df['skel_node_count','sum']/df['skel_total_length','sum']) + (df['skel_brh_count','sum']/df['skel_total_length','sum']),
        skel_connectivity = lambda df: df['skel_fusion_score']/df['skel_fission_score'],
        skel_heterogeneity = lambda df: (df['skel_node_count','std']/df['skel_node_count','mean']) + 
            (df['skel_brh_count','std']/df['skel_brh_count','mean']) +
            (df['skel_total_length','std']/df['skel_total_length','mean']) +
            (df['volume','std']/df['volume','mean']) +
            (df['skel_width','std']/df['skel_width','mean']) +
            df['skel_avg_node_deg']
    )

    # columns from the fusion/fission table to add to the morphology summary table
    skel_sum_metrics = ["punctate_count", "rod_count", "iso_cycle_count", "network_count",
        "skel_avg_node_deg", "skel_fusion_score", "skel_fission_score", "skel_connectivity", "skel_heterogeneity"]

    # merge these additional metrics back into the org_summary table
    org_summary = pd.merge(org_summary, skel_ff[skel_sum_metrics], on=group_by, how='outer')

print("Organelle morphology summary statistics:")
org_summary

Organelle morphology summary statistics:

                                                                                                                              org  \
                                                                                                                            count
dataset                       image_name                                          mask_name scale                    object
test_dataset_1                05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER         1
                                                                                                                     LD         3
                                                                                                                     golgi     95
                                                                                                                     lyso     501
                                                                                                                     mito     282
                                                                                                                     perox    319
test_dataset_1-comparison     05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER         1
                                                                                                                     LD         3
                                                                                                                     golgi     95
                                                                                                                     lyso     501
                                                                                                                     mito     282
                                                                                                                     perox    319
test_dataset_1-testcomparison 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER         1
                                                                                                                     LD         3
                                                                                                                     golgi     95
                                                                                                                     lyso     501
                                                                                                                     mito     282
                                                                                                                     perox    319

                                                                                                                                  volume  \
                                                                                                                                     sum
dataset                       image_name                                          mask_name scale                    object
test_dataset_1                05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      1633.166259
                                                                                                                     LD         0.455692
                                                                                                                     golgi     52.786906
                                                                                                                     lyso     725.500337
                                                                                                                     mito     200.000880
                                                                                                                     perox    114.933228
test_dataset_1-comparison     05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      1633.166259
                                                                                                                     LD         0.455692
                                                                                                                     golgi     52.786906
                                                                                                                     lyso     725.500337
                                                                                                                     mito     200.000880
                                                                                                                     perox    114.933228
test_dataset_1-testcomparison 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      1633.166259
                                                                                                                     LD         0.455692
                                                                                                                     golgi     52.786906
                                                                                                                     lyso     725.500337
                                                                                                                     mito     200.000880
                                                                                                                     perox    114.933228

                                                                                                                                       \
                                                                                                                             fraction
dataset                       image_name                                          mask_name scale                    object
test_dataset_1                05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      0.409385
                                                                                                                     LD      0.000114
                                                                                                                     golgi   0.013232
                                                                                                                     lyso    0.181861
                                                                                                                     mito    0.050134
                                                                                                                     perox   0.028810
test_dataset_1-comparison     05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      0.409385
                                                                                                                     LD      0.000114
                                                                                                                     golgi   0.013232
                                                                                                                     lyso    0.181861
                                                                                                                     mito    0.050134
                                                                                                                     perox   0.028810
test_dataset_1-testcomparison 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      0.409385
                                                                                                                     LD      0.000114
                                                                                                                     golgi   0.013232
                                                                                                                     lyso    0.181861
                                                                                                                     mito    0.050134
                                                                                                                     perox   0.028810

                                                                                                                                          \
                                                                                                                                    mean
dataset                       image_name                                          mask_name scale                    object
test_dataset_1                05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      1633.166259
                                                                                                                     LD         0.151897
                                                                                                                     golgi      0.555652
                                                                                                                     lyso       1.448104
                                                                                                                     mito       0.709223
                                                                                                                     perox      0.360292
test_dataset_1-comparison     05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      1633.166259
                                                                                                                     LD         0.151897
                                                                                                                     golgi      0.555652
                                                                                                                     lyso       1.448104
                                                                                                                     mito       0.709223
                                                                                                                     perox      0.360292
test_dataset_1-testcomparison 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      1633.166259
                                                                                                                     LD         0.151897
                                                                                                                     golgi      0.555652
                                                                                                                     lyso       1.448104
                                                                                                                     mito       0.709223
                                                                                                                     perox      0.360292

                                                                                                                                          \
                                                                                                                                  median
dataset                       image_name                                          mask_name scale                    object
test_dataset_1                05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      1633.166259
                                                                                                                     LD         0.083544
                                                                                                                     golgi      0.058227
                                                                                                                     lyso       0.098733
                                                                                                                     mito       0.254428
                                                                                                                     perox      0.177214
test_dataset_1-comparison     05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      1633.166259
                                                                                                                     LD         0.083544
                                                                                                                     golgi      0.058227
                                                                                                                     lyso       0.098733
                                                                                                                     mito       0.254428
                                                                                                                     perox      0.177214
test_dataset_1-testcomparison 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      1633.166259
                                                                                                                     LD         0.083544
                                                                                                                     golgi      0.058227
                                                                                                                     lyso       0.098733
                                                                                                                     mito       0.254428
                                                                                                                     perox      0.177214

                                                                                                                                        \
                                                                                                                                   std
dataset                       image_name                                          mask_name scale                    object
test_dataset_1                05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER            NaN
                                                                                                                     LD       0.152466
                                                                                                                     golgi    3.352017
                                                                                                                     lyso    25.649103
                                                                                                                     mito     1.468134
                                                                                                                     perox    0.731846
test_dataset_1-comparison     05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER            NaN
                                                                                                                     LD       0.152466
                                                                                                                     golgi    3.352017
                                                                                                                     lyso    25.649103
                                                                                                                     mito     1.468134
                                                                                                                     perox    0.731846
test_dataset_1-testcomparison 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER            NaN
                                                                                                                     LD       0.152466
                                                                                                                     golgi    3.352017
                                                                                                                     lyso    25.649103
                                                                                                                     mito     1.468134
                                                                                                                     perox    0.731846

                                                                                                                            surface_area  \
                                                                                                                                     sum
dataset                       image_name                                          mask_name scale                    object
test_dataset_1                05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      8152.582980
                                                                                                                     LD         8.249761
                                                                                                                     golgi    510.803918
                                                                                                                     lyso    3920.748076
                                                                                                                     mito    3170.253637
                                                                                                                     perox   1466.429375
test_dataset_1-comparison     05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      8152.582980
                                                                                                                     LD         8.249761
                                                                                                                     golgi    510.803918
                                                                                                                     lyso    3920.748076
                                                                                                                     mito    3170.253637
                                                                                                                     perox   1466.429375
test_dataset_1-testcomparison 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      8152.582980
                                                                                                                     LD         8.249761
                                                                                                                     golgi    510.803918
                                                                                                                     lyso    3920.748076
                                                                                                                     mito    3170.253637
                                                                                                                     perox   1466.429375

                                                                                                                                          \

#### **`STEP 3` - Ensure all organelles included in the analysis are represented and fill NA values with 0 as needed**

##### &#x1F3C3; **Run code; no user input required**

&#x1F453; **FYI:** The block of code below adds any organelles that were missing from the analysis (no organelle objects in images) and represents their volumes and counts with 0. If any objects have a count of 1, the standard deviation value is changes to NA.

In [28]:
###################
# fill gaps & NA values
###################
# Ensure all possible interactions are represented (if missing fill with NaN)
for ind in org_summary.index.droplevel(4).unique().to_list():
    for row in org_file_names:
        if ind+(row,) not in org_summary.index:
            org_summary.loc[ind+(row,)] = np.nan

# fill NA with 0 for specific columns
fill_dict = {('org', 'count'): 0, 
             ('volume', 'sum'): 0,
             ('surface_area', 'sum'): 0,
             ('volume', 'fraction'): 0}
org_summary = org_summary.fillna(value=fill_dict)

# if (org, count) is 1, set mean, median, and std to NaN
single_site_mask = org_summary[('org', 'count')] == 1
for col in sharedcolumns+['volume', 'surface_area']:
    org_summary.loc[single_site_mask, (col, 'std')] = np.nan

org_summary.sort_index(inplace=True)

print("Morphology summary of interaction sites per image (or mask region):")
display(org_summary.head(7))

Morphology summary of interaction sites per image (or mask region):

                                                                                                                          org  \
                                                                                                                        count
dataset                   image_name                                          mask_name scale                    object
test_dataset_1            05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER         1
                                                                                                                 LD         3
                                                                                                                 golgi     95
                                                                                                                 lyso     501
                                                                                                                 mito     282
                                                                                                                 perox    319
test_dataset_1-comparison 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER         1

                                                                                                                              volume  \
                                                                                                                                 sum
dataset                   image_name                                          mask_name scale                    object
test_dataset_1            05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      1633.166259
                                                                                                                 LD         0.455692
                                                                                                                 golgi     52.786906
                                                                                                                 lyso     725.500337
                                                                                                                 mito     200.000880
                                                                                                                 perox    114.933228
test_dataset_1-comparison 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      1633.166259

                                                                                                                                   \
                                                                                                                         fraction
dataset                   image_name                                          mask_name scale                    object
test_dataset_1            05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      0.409385
                                                                                                                 LD      0.000114
                                                                                                                 golgi   0.013232
                                                                                                                 lyso    0.181861
                                                                                                                 mito    0.050134
                                                                                                                 perox   0.028810
test_dataset_1-comparison 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      0.409385

                                                                                                                                      \
                                                                                                                                mean
dataset                   image_name                                          mask_name scale                    object
test_dataset_1            05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      1633.166259
                                                                                                                 LD         0.151897
                                                                                                                 golgi      0.555652
                                                                                                                 lyso       1.448104
                                                                                                                 mito       0.709223
                                                                                                                 perox      0.360292
test_dataset_1-comparison 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      1633.166259

                                                                                                                                      \
                                                                                                                              median
dataset                   image_name                                          mask_name scale                    object
test_dataset_1            05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      1633.166259
                                                                                                                 LD         0.083544
                                                                                                                 golgi      0.058227
                                                                                                                 lyso       0.098733
                                                                                                                 mito       0.254428
                                                                                                                 perox      0.177214
test_dataset_1-comparison 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      1633.166259

                                                                                                                                    \
                                                                                                                               std
dataset                   image_name                                          mask_name scale                    object
test_dataset_1            05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER            NaN
                                                                                                                 LD       0.152466
                                                                                                                 golgi    3.352017
                                                                                                                 lyso    25.649103
                                                                                                                 mito     1.468134
                                                                                                                 perox    0.731846
test_dataset_1-comparison 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER            NaN

                                                                                                                        surface_area  \
                                                                                                                                 sum
dataset                   image_name                                          mask_name scale                    object
test_dataset_1            05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      8152.582980
                                                                                                                 LD         8.249761
                                                                                                                 golgi    510.803918
                                                                                                                 lyso    3920.748076
                                                                                                                 mito    3170.253637
                                                                                                                 perox   1466.429375
test_dataset_1-comparison 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      8152.582980

                                                                                                                                      \
                                                                                                                                mean
dataset                   image_name                                          mask_name scale                    object
test_dataset_1            05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      8152.582980
                                                                                                                 LD         2.749920
                                                                                                                 golgi      5.376883
                                                                                                                 lyso       7.825844
                                                                                                                 mito      11.242034
                                                                                                                 perox      4.596957
test_dataset_1-comparison 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      8152.582980

                                                                                                                                      \
                                                                                                                              median
dataset                   image_name                                          mask_name scale                    object
test_dataset_1            05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      8152.582980
                                                                                                                 LD         2.191399
                                                                                                                 golgi      1.406250
                                                                                                                 lyso       1.986249
                                                                                                                 mito       4.268804
                                                                                                                 perox      2.755472
test_dataset_1-comparison 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      8152.582980

                                                                                                                                    \
                                                                                                                               std
dataset                   image_name                                          mask_name scale                    object
test_dataset_1            05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER            NaN
                                                                                                                 LD       1.729692
                                                                                                                 golgi   24.986952
                                                                                                                 lyso    93.700820
                                                                                                                 mito    22.119440
                                                                                                                 perox    7.008761
test_dataset_1-comparison 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER            NaN

                                                                                                                        SA_to_volume_ratio  \
                                                                                                                                      mean
dataset                   image_name                                          mask_name scale                    object
test_dataset_1            05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER               4.991888
                                                                                                                 LD              23.540761
                                                                                                                 golgi           24.160999
                                                                                                                 lyso            20.991357
                                                                                                                 mito            21.980178
                                                                                                                 perox           17.687814
test_dataset_1-comparison 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER               4.991888

                                                                                                                                    \
                                                                                                                            median
dataset                   image_name                                          mask_name scale                    object
test_dataset_1            05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER       4.991888
                                                                                                                 LD      26.230594
                                                                                                                 golgi   25.205701
                                                                                                                 lyso    20.117305
                                                                                                                 mito    17.329224
                                                                                                                 perox   15.518633
test_dataset_1-comparison 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER       4.991888

                                                                                                                                   \
                                                                                                                              std
dataset                   image_name                                          mask_name scale                    object
test_dataset_1            05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER           NaN
                                                                                                                 LD      8.174231
                                                                                                                 golgi   6.956939
                                                                                                                 lyso    8.056135
                                                                                                                 mito    8.787985
                                                                                                                 perox   6.399205
test_dataset_1-comparison 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER           NaN

                                                                                                                        equivalent_diameter  \
                                                                                                                                       mean
dataset                   image_name                                          mask_name scale                    object
test_dataset_1            05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER               14.610910
                                                                                                                 LD                0.613314
                                                                                                                 golgi             0.600860
                                                                                                                 lyso              0.691336
                                                                                                                 mito              0.871884
                                                                                                                 perox             0.754789
test_dataset_1-comparison 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER               14.610910

                                                                                                                                    \
                                                                                                                            median
dataset                   image_name                                          mask_name scale                    object
test_dataset_1            05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      14.610910
                                                                                                                 LD       0.542382
                                                                                                                 golgi    0.480887
                                                                                                                 lyso     0.573441
                                                                                                                 mito     0.786161
                                                                                                                 perox    0.696893
test_dataset_1-comparison 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      14.610910

                                                                                                                                   \

#### **`STEP 4` - Unstack the organelle names and save file**

#### &#x1F6D1; &#x270D; **User Input Required:**

&#x1F453; **FYI:** In this step each table is reformated to "unstack" the organelle column into the rows. In the resulting table, each row corresponds to a single image. The table is then exported.

Please specify if the interactions degree analysis should be carried out:
- `out_prefix`: A string used to name the output files. For example, if "date" is specified as out_prefix, the output files would be named "date_org_morphology_summarystats.csv".

In [ ]:
### USER INPUT REQUIRED ###
out_prefix = "all_datasets_1"

##### &#x1F3C3; **Run code; no user input required**

&#x1F453; **FYI:** The block of code below the following action occur:
1. The "organelle" column was unstacked resulting in a dataframe where each column if a different summary statistic and row represents the values for each cell. 
2. For specific values, such as organelle count and total/mean/median volume, NA values were filled with 0.
3. The standard deviation, mean, and median values for the ER (forced to be only one object) were removed.
4. The file was saved.

In [32]:
###################
# flatten datasheet and export
###################
# export before unstacking
if (Path(quant_data_path) / f"{out_prefix}_per_org_morphology_summarystats.csv").exists():
    raise FileExistsError(f"CAUTION: {out_prefix}_per_org_morphology_summarystats.csv already exists and will not be overwritten. Move the existing file, change the `out_prefix` or `quant_data_path` to continue without error.")
else:
    org_summary.to_csv(str(quant_data_path) + f"/{out_prefix}_per_org_morphology_summarystats.csv", mode='x')
    print(f"Exported per-organelle morphology summary statistics (before unstacking) to {quant_data_path}/{out_prefix}_per_org_morphology_summarystats.csv")

org_morph_final = org_summary.unstack(-1)
org_morph_final.columns = ["_".join((col_name[1], col_name[-1], col_name[0])) for col_name in org_morph_final.columns.to_flat_index()]
org_morph_final.columns = [col.replace('sum', 'total') for col in org_morph_final.columns]
org_morph_final.columns = [col.replace(col, 'mask_volume') if 'mask' in col else col for col in org_morph_final.columns]
org_morph_final = org_morph_final.loc[:, ~org_morph_final.columns.duplicated()]
org_morph_final.reset_index(inplace=True)
print("The morphology summary after unstacking:")
display(org_morph_final)

###################
# export summary sheets
###################
if (Path(quant_data_path) / f"{out_prefix}_organelle_morphology_summarystats.csv").exists():
    raise FileExistsError(f"CAUTION: {out_prefix}_organelle_morphology_summarystats.csv already exists and will not be overwritten. Move the existing file, change the `out_prefix` or `quant_data_path` to continue without error.")
else:
    org_morph_final.to_csv(str(quant_data_path) + f"/{out_prefix}_organelle_morphology_summarystats.csv", mode='x')
    print(f"Exported organelle morphology summary statistics (after unstacking) to {quant_data_path}/{out_prefix}_organelle_morphology_summarystats.csv")

Exported per-organelle morphology summary statistics (before unstacking) to C:\Users\redre\Documents\CohenLab\scohen_lab_repo\infer-subc\sample_data\example_quant\quant/all_datasets_2_per_org_morphology_summarystats.csv
The morphology summary after unstacking:

,dataset,image_name,mask_name,scale,count_ER_org,count_LD_org,count_golgi_org,count_lyso_org,count_mito_org,count_perox_org,total_ER_volume,total_LD_volume,total_golgi_volume,total_lyso_volume,total_mito_volume,total_perox_volume,fraction_ER_volume,fraction_LD_volume,fraction_golgi_volume,fraction_lyso_volume,fraction_mito_volume,fraction_perox_volume,mean_ER_volume,mean_LD_volume,mean_golgi_volume,mean_lyso_volume,mean_mito_volume,mean_perox_volume,median_ER_volume,median_LD_volume,median_golgi_volume,median_lyso_volume,median_mito_volume,median_perox_volume,std_ER_volume,std_LD_volume,std_golgi_volume,std_lyso_volume,std_mito_volume,std_perox_volume,total_ER_surface_area,total_LD_surface_area,total_golgi_surface_area,total_lyso_surface_area,total_mito_surface_area,total_perox_surface_area,mean_ER_surface_area,mean_LD_surface_area,mean_golgi_surface_area,mean_lyso_surface_area,mean_mito_surface_area,mean_perox_surface_area,median_ER_surface_area,median_LD_surface_area,median_golgi_surface_area,median_lyso_surface_area,median_mito_surface_area,median_perox_surface_area,std_ER_surface_area,std_LD_surface_area,std_golgi_surface_area,std_lyso_surface_area,std_mito_surface_area,std_perox_surface_area,mean_ER_SA_to_volume_ratio,mean_LD_SA_to_volume_ratio,mean_golgi_SA_to_volume_ratio,mean_lyso_SA_to_volume_ratio,mean_mito_SA_to_volume_ratio,mean_perox_SA_to_volume_ratio,median_ER_SA_to_volume_ratio,median_LD_SA_to_volume_ratio,median_golgi_SA_to_volume_ratio,median_lyso_SA_to_volume_ratio,median_mito_SA_to_volume_ratio,median_perox_SA_to_volume_ratio,std_ER_SA_to_volume_ratio,std_LD_SA_to_volume_ratio,std_golgi_SA_to_volume_ratio,std_lyso_SA_to_volume_ratio,std_mito_SA_to_volume_ratio,std_perox_SA_to_volume_ratio,mean_ER_equivalent_diameter,mean_LD_equivalent_diameter,mean_golgi_equivalent_diameter,mean_lyso_equivalent_diameter,mean_mito_equivalent_diameter,mean_perox_equivalent_diameter,median_ER_equivalent_diameter,median_LD_equivalent_diameter,median_golgi_equivalent_diameter,median_lyso_equivalent_diameter,median_mito_equivalent_diameter,median_perox_equivalent_diameter,std_ER_equivalent_diameter,std_LD_equivalent_diameter,std_golgi_equivalent_diameter,std_lyso_equivalent_diameter,std_mito_equivalent_diameter,std_perox_equivalent_diameter,mean_ER_extent,mean_LD_extent,mean_golgi_extent,mean_lyso_extent,mean_mito_extent,mean_perox_extent,median_ER_extent,median_LD_extent,median_golgi_extent,median_lyso_extent,median_mito_extent,median_perox_extent,std_ER_extent,std_LD_extent,std_golgi_extent,std_lyso_extent,std_mito_extent,std_perox_extent,mean_ER_euler_number,mean_LD_euler_number,mean_golgi_euler_number,mean_lyso_euler_number,mean_mito_euler_number,mean_perox_euler_number,median_ER_euler_number,median_LD_euler_number,median_golgi_euler_number,median_lyso_euler_number,median_mito_euler_number,median_perox_euler_number,std_ER_euler_number,std_LD_euler_number,std_golgi_euler_number,std_lyso_euler_number,std_mito_euler_number,std_perox_euler_number,mean_ER_solidity,mean_LD_solidity,mean_golgi_solidity,mean_lyso_solidity,mean_mito_solidity,mean_perox_solidity,median_ER_solidity,median_LD_solidity,median_golgi_solidity,median_lyso_solidity,median_mito_solidity,median_perox_solidity,std_ER_solidity,std_LD_solidity,std_golgi_solidity,std_lyso_solidity,std_mito_solidity,std_perox_solidity,mean_ER_axis_major_length,mean_LD_axis_major_length,mean_golgi_axis_major_length,mean_lyso_axis_major_length,mean_mito_axis_major_length,mean_perox_axis_major_length,median_ER_axis_major_length,median_LD_axis_major_length,median_golgi_axis_major_length,median_lyso_axis_major_length,median_mito_axis_major_length,median_perox_axis_major_length,std_ER_axis_major_length,std_LD_axis_major_length,std_golgi_axis_major_length,std_lyso_axis_major_length,std_mito_axis_major_length,std_perox_axis_major_length,total_ER_skel_total_length,total_LD_skel_total_length,total_golgi_skel_total_length,total_lyso_skel_total_length,total_mito_skel_total_length,total_perox_skel_total_length,mean_ER_skel_total_length,mean_LD_skel_total_length,mean_golgi_skel_total_length,mean_lyso_skel_total_length,mean_mito_skel_total_length,mean_perox_skel_total_length,median_ER_skel_total_length,median_LD_skel_total_length,median_golgi_skel_total_length,median_lyso_skel_total_length,median_mito_skel_total_length,median_perox_skel_total_length,std_ER_skel_total_length,std_LD_skel_total_length,std_golgi_skel_total_length,std_lyso_skel_total_length,std_mito_skel_total_length,std_perox_skel_total_length,total_ER_skel_abs_punc_count,total_LD_skel_abs_punc_count,total_golgi_skel_abs_punc_count,total_lyso_skel_abs_punc_count,total_mito_skel_abs_punc_count,total_perox_skel_abs_punc_count,mean_ER_skel_abs_punc_count,mean_LD_skel_abs_punc_count,mean_golgi_skel_abs_punc_count,mean_lyso_skel_abs_punc_count,mean_mito_skel_abs_punc_count,mean_perox_skel_abs_punc_count,median_ER_skel_abs_punc_count,median_LD_skel_abs_punc_count,median_golgi_skel_abs_punc_count,median_lyso_skel_abs_punc_count,median_mito_skel_abs_punc_count,median_perox_skel_abs_punc_count,std_ER_skel_abs_punc_count,std_LD_skel_abs_punc_count,std_golgi_skel_abs_punc_count,std_lyso_skel_abs_punc_count,std_mito_skel_abs_punc_count,std_perox_skel_abs_punc_count,total_ER_skel_ep_count,total_LD_skel_ep_count,total_golgi_skel_ep_count,total_lyso_skel_ep_count,total_mito_skel_ep_count,total_perox_skel_ep_count,mean_ER_skel_ep_count,mean_LD_skel_ep_count,mean_golgi_skel_ep_count,mean_lyso_skel_ep_count,mean_mito_skel_ep_count,mean_perox_skel_ep_count,median_ER_skel_ep_count,median_LD_skel_ep_count,median_golgi_skel_ep_count,median_lyso_skel_ep_count,median_mito_skel_ep_count,median_perox_skel_ep_count,std_ER_skel_ep_count,std_LD_skel_ep_count,std_golgi_skel_ep_count,std_lyso_skel_ep_count,std_mito_skel_ep_count,std_perox_skel_ep_count,total_ER_skel_jn_count,total_LD_skel_jn_count,total_golgi_skel_jn_count,total_lyso_skel_jn_count,total_mito_skel_jn_count,total_perox_skel_jn_count,mean_ER_skel_jn_count,mean_LD_skel_jn_count,mean_golgi_skel_jn_count,mean_lyso_skel_jn_count,mean_mito_skel_jn_count,mean_perox_skel_jn_count,median_ER_skel_jn_count,median_LD_skel_jn_count,median_golgi_skel_jn_count,median_lyso_skel_jn_count,median_mito_skel_jn_count,median_perox_skel_jn_count,std_ER_skel_jn_count,std_LD_skel_jn_count,std_golgi_skel_jn_count,std_lyso_skel_jn_count,std_mito_skel_jn_count,std_perox_skel_jn_count,total_ER_skel_node_count,total_LD_skel_node_count,total_golgi_skel_node_count,total_lyso_skel_node_count,total_mito_skel_node_count,total_perox_skel_node_count,mean_ER_skel_node_count,mean_LD_skel_node_count,mean_golgi_skel_node_count,mean_lyso_skel_node_count,mean_mito_skel_node_count,mean_perox_skel_node_count,median_ER_skel_node_count,median_LD_skel_node_count,median_golgi_skel_node_count,median_lyso_skel_node_count,median_mito_skel_node_count,median_perox_skel_node_count,std_ER_skel_node_count,std_LD_skel_node_count,std_golgi_skel_node_count,std_lyso_skel_node_count,std_mito_skel_node_count,std_perox_skel_node_count,total_ER_skel_brh_count,total_LD_skel_brh_count,total_golgi_skel_brh_count,total_lyso_skel_brh_count,total_mito_skel_brh_count,total_perox_skel_brh_count,mean_ER_skel_brh_count,mean_LD_skel_brh_count,mean_golgi_skel_brh_count,mean_lyso_skel_brh_count,mean_mito_skel_brh_count,mean_perox_skel_brh_count,median_ER_skel_brh_count,median_LD_skel_brh_count,median_golgi_skel_brh_count,median_lyso_skel_brh_count,median_mito_skel_brh_count,median_perox_skel_brh_count,std_ER_skel_brh_count,std_LD_skel_brh_count,std_golgi_skel_brh_count,std_lyso_skel_brh_count,std_mito_skel_brh_count,std_perox_skel_brh_count,mean_ER_skel_brh_type_0_tot,mean_LD_skel_brh_type_0_tot,mean_golgi_skel_brh_type_0_tot,mean_lyso_skel_brh_type_0_tot,mean_mito_skel_brh_type_0_tot,mean_perox_skel_brh_type_0_tot,median_ER_skel_brh_type_0_tot,median_LD_skel_brh_type_0_tot,median_golgi_skel_brh_type_0_tot,median_lyso_skel_brh_type_0_tot,median_mito_skel_brh_type_0_tot,median_perox_skel_brh_type_0_tot,std_ER_skel_brh_type_0_tot,std_LD_skel_brh_type_0_tot,std_golgi_skel_brh_type_0_tot,std_lyso_skel_brh_type_0_tot,std_mito_skel_brh_type_0_tot,std_perox_skel_brh_type_0_tot,mean_ER_skel_brh_type_1_tot,mean_LD_skel_brh_type_1_tot,mean_golgi_skel_brh_type_1_tot,mean_lyso_skel_brh_type_1_tot,mean_mito_skel_brh_type_1_tot,mean_perox_skel_brh_type_1_tot,median_ER_skel_brh_type_1_tot,median_LD_skel_brh_type_1_tot,median_golgi_skel_brh_type_1_tot,median_lyso_skel_brh_type_1_tot,median_mito_skel_brh_type_1_tot,median_perox_skel_brh_type_1_tot,std_ER_skel_brh_type_1_tot,std_LD_skel_brh_type_1_tot,std_golgi_skel_brh_type_1_tot,std_lyso_skel_brh_type_1_tot,std_mito_skel_brh_type_1_tot,std_perox_skel_brh_type_1_tot,mean_ER_skel_brh_type_2_tot,mean_LD_skel_brh_type_2_tot,mean_golgi_skel_brh_type_2_tot,mean_lyso_skel_brh_type_2_tot,mean_mito_skel_brh_type_2_tot,mean_perox_skel_brh_type_2_tot,median_ER_skel_brh_type_2_tot,median_LD_skel_brh_type_2_tot,median_golgi_skel_brh_type_2_tot,median_lyso_skel_brh_type_2_tot,median_mito_skel_brh_type_2_tot,median_perox_skel_brh_type_2_tot,std_ER_skel_brh_type_2_tot,std_LD_skel_brh_type_2_tot,std_golgi_skel_brh_type_2_tot,std_lyso_skel_brh_type_2_tot,std_mito_skel_brh_type_2_tot,std_perox_skel_brh_type_2_tot,mean_ER_skel_brh_type_3_tot,mean_LD_skel_brh_type_3_tot,mean_golgi_skel_brh_type_3_tot,mean_lyso_skel_brh_type_3_tot,mean_mito_skel_brh_type_3_tot,mean_perox_skel_brh_type_3_tot,median_ER_skel_brh_type_3_tot,median_LD_skel_brh_type_3_tot,median_golgi_skel_brh_type_3_tot,median_lyso_skel_brh_type_3_tot,median_mito_skel_brh_type_3_tot,median_perox_skel_brh_type_3_tot,std_ER_skel_brh_type_3_tot,std_LD_skel_brh_type_3_tot,std_golgi_skel_brh_type_3_tot,std_lyso_skel_brh_type_3_tot,std_mito_skel_brh_type_3_tot,std_perox_skel_brh_type_3_tot,mean_ER_skel_comp_count,mean_LD_skel_comp_count,mean_golgi_skel_comp_count,mean_lyso_skel_comp_count,mean_mito_skel_comp_count,mean_perox_skel_comp_count,median_ER_skel_comp_count,median_LD_skel_comp_count,median_golgi_skel_comp_count,median_lyso_skel_comp_count,median_mito_skel_comp_count,median_perox_skel_comp_count,std_ER_skel_comp_count,std_LD_skel_comp_count,std_golgi_skel_comp_count,std_lyso_skel_comp_count,std_mito_skel_comp_count,std_perox_skel_comp_count,mean_ER_skel_ave_jn_deg,mean_LD_skel_ave_jn_deg,mean_golgi_skel_ave_jn_deg,mean_lyso_skel_ave_jn_deg,mean_mito_skel_ave_jn_deg,mean_perox_skel_ave_jn_deg,median_ER_skel_ave_jn_deg,median_LD_skel_ave_jn_deg,median_golgi_skel_ave_jn_deg,median_lyso_skel_ave_jn_deg,median_mito_skel_ave_jn_deg,median_perox_skel_ave_jn_deg,std_ER_skel_ave_jn_deg,std_LD_skel_ave_jn_deg,std_golgi_skel_ave_jn_deg,std_lyso_skel_ave_jn_deg,std_mito_skel_ave_jn_deg,std_perox_skel_ave_jn_deg,mean_ER_skel_max_deg,mean_LD_skel_max_deg,mean_golgi_skel_max_deg,mean_lyso_skel_max_deg,mean_mito_skel_max_deg,mean_perox_skel_max_deg,median_ER_skel_max_deg,median_LD_skel_max_deg,median_golgi_skel_max_deg,median_lyso_skel_max_deg,median_mito_skel_max_deg,median_perox_skel_max_deg,std_ER_skel_max_deg,std_LD_skel_max_deg,std_golgi_skel_max_deg,std_lyso_skel_max_deg,std_mito_skel_max_deg,std_perox_skel_max_deg,mean_ER_skel_mean_brh_str,mean_LD_skel_mean_brh_str,mean_golgi_skel_mean_brh_str,mean_lyso_skel_mean_brh_str,mean_mito_skel_mean_brh_str,mean_perox_skel_mean_brh_str,median_ER_skel_mean_brh_str,median_LD_skel_mean_brh_str,median_golgi_skel_mean_brh_str,median_lyso_skel_mean_brh_str,median_mito_skel_mean_brh_str,median_perox_skel_mean_brh_str,std_ER_skel_mean_brh_str,std_LD_skel_mean_brh_str,std_golgi_skel_mean_brh_str,std_lyso_skel_mean_brh_str,std_mito_skel_mean_brh_str,std_perox_skel_mean_brh_str,mean_ER_skel_width,mean_LD_skel_width,mean_golgi_skel_width,mean_lyso_skel_width,mean_mito_skel_width,mean_perox_skel_width,median_ER_skel_width,median_LD_skel_width,median_golgi_skel_width,median_lyso_skel_width,median_mito_skel_width,median_perox_skel_width,std_ER_skel_width,std_LD_skel_width,std_golgi_skel_width,std_lyso_skel_width,std_mito_skel_width,std_perox_skel_width,_ER_punctate_count,_LD_punctate_count,_golgi_punctate_count,_lyso_punctate_count,_mito_punctate_count,_perox_punctate_count,_ER_rod_count,_LD_rod_count,_golgi_rod_count,_lyso_rod_count,_mito_rod_count,_perox_rod_count,_ER_iso_cycle_count,_LD_iso_cycle_count,_golgi_iso_cycle_count,_lyso_iso_cycle_count,_mito_iso_cycle_count,_perox_iso_cycle_count,_ER_network_count,_LD_network_count,_golgi_network_count,_lyso_network_count,_mito_network_count,_perox_network_count,_ER_skel_avg_node_deg,_LD_skel_avg_node_deg,_golgi_skel_avg_node_deg,_lyso_skel_avg_node_deg,_mito_skel_avg_node_deg,_perox_skel_avg_node_deg,_ER_skel_fusion_score,_LD_skel_fusion_score,_golgi_skel_fusion_score,_lyso_skel_fusion_score,_mito_skel_fusion_score,_perox_skel_fusion_score,_ER_skel_fission_score,_LD_skel_fission_score,_golgi_skel_fission_score,_lyso_skel_fission_score,_mito_skel_fission_score,_perox_skel_fission_score,_ER_skel_connectivity,_LD_skel_connectivity,_golgi_skel_connectivity,_lyso_skel_connectivity,_mito_skel_connectivity,_perox_skel_connectivity,_ER_skel_heterogeneity,_LD_skel_heterogeneity,_golgi_skel_heterogeneity,_lyso_skel_heterogeneity,_mito_skel_heterogeneity,_perox_skel_heterogeneity
0,test_dataset_1,05052022_astro_control_2_Linear unmixing_0_cmle.ome,cell,"(0.3961, 0.0799, 0.0799)",1,3,95,501,282,319,1633.166259,0.455692,52.786906,725.500337,200.00088,114.933228,0.409385,0.000114,0.013232,0.181861,0.050134,0.02881,1633.166259,0.151897,0.555652,1.448104,0.709223,0.360292,1633.166259,0.083544,0.058227,0.098733,0.254428,0.177214,NaN,0.152466,3.352017,25.649103,1.468134,0.731846,8152.58298,8.249761,510.803918,3920.748076,3170.253637,1466.429375,8152.58298,2.74992,5.376883,7.825844,11.242034,4.596957,8152.58298,2.191399,1.40625,1.986249,4.268804,2.755472,NaN,1.729692,24.986952,93.70082,22.11944,7.008761,4.991888,23.540761,24.160999,20.991357,21.980178,17.687814,4.991888,26.230594,25.205701,20.117305,17.329224,15.518633,NaN,8.174231,6.956939,8.056135,8.787985,6.399205,14.61091,0.613314,0.60086,0.691336,0.871884,0.754789,14.61091,0.542382,0.480887,0.573441,0.786161,0.696893,NaN,0.214604,0.458414,0.541158,0.462326,0.302679,0.015125,0.419604,0.620365,0.538277,0.282446,0.459492,0.015125,0.336735,0.666667,0.488095,0.250744,0.444444,NaN,0.19547,0.240021,0.231139,0.198523,0.215976,-379.0,0.666667,0.905263,0.678643,0.815603,0.978056,-379.0,1.0,1.0,1.0,1.0,1.0,NaN,0.57735,0.730399,6.614115,0.783303,0.216071,0.104462,inf,inf,inf,inf,inf,0.104462,0.638614,inf,0.843137,0.6755,0.8,NaN,NaN,NaN,NaN,NaN,NaN,113.933103,1.09351,1.030799,1.126975,2.714379,1.390219,113.933103,1.025454,0.574356,0.879324,1.664386,1.088984,NaN,0.44736,1.65298,1.476231,2.82197,0.98195,4859.651249,0.612143,148.443684,1587.771496,1401.735015,348.968525,4859.651249,0.204048,1.562565,3.169205,4.970692,1.093945,4859.651249,0.272956,0.113062,0.113062,1.231977,0.113062,NaN,0.179786,9.452285,54.595922,12.111393,3.033922,46,0,32,148,45,119,46.0,0.0,0.336842,0.295409,0.159574,0.373041,46.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.475138,0.456682,0.376437,0.484373,4308,4,154,1404,702,464,4308.0,1.333333,1.621053,2.802395,2.489362,1.454545,4308.0,2.0,2.0,2.0,2.0,2.0,NaN,1.154701,2.484758,27.934117,3.017427,1.467779,4359,0,45,928,315,73,4359.0,0.0,0.473684,1.852295,1.117021,0.22884,4359.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,3.542574,37.443426,4.153264,1.102163,8713,4,231,2480,1062,656,8713.0,1.333333,2.431579,4.9501,3.765957,2.056426,8713.0,2.0,2.0,2.0,2.0,2.0,NaN,1.154701,5.808381,65.347192,7.016136,2.150753,9129,2,145,2150,826,342,9129.0,0.666667,1.526316,4.291417,2.929078,1.0721,9129.0,1.0,1.0,1.0,1.0,1.0,NaN,0.57735,6.526284,72.581726,7.714335,2.242627,160.0,0.666667,0.610526,0.628743,0.641844,0.539185,160.0,1.0,1.0,1.0,1.0,1.0,NaN,0.57735,0.490218,0.487742,0.494907,0.505505,3988.0,0.0,0.4,1.54491,1.205674,0.376176,3988.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,2.48998,27.984719,3.340718,1.363102,4980.0,0.0,0.505263,2.113772,1.067376,0.15047,4980.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,4.143371,44.635782,4.662152,1.038228,1.0,0.0,0.010526,0.003992,0.014184,0.00627,1.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.102598,0.063119,0.118461,0.079056,228.0,1.0,1.0,1.007984,1.024823,1.009404,228.0,1.0,1.0,1.0,1.0,1.0,NaN,0.0,0.0,0.126238,0.196284,0.125038,3.200275,NaN,3.005882,3.006071,3.006595,3.00431,3.200275,NaN,3.0,3.0,3.0,3.0,NaN,NaN,0.013153,0.027185,0.027267,0.023212,4.0,2.0,1.178947,1.245509,1.879433,1.191223,4.0,2.0,1.0,1.0,2.0,1.0,NaN,0.0,0.989078,0.978573,0.958017,1.048112,0.897746,0.963105,0.896843,0.890067,0.750664,0.823294,0.897746,0.963105,1.0,0.941784,0.761127,0.837543,NaN,0.052178,0.145104,0.137817,0.189559,0.169249,0.290945,0.0,0.002538,0.038299,0.081324,0.035456,0.290945,0.0,0.0,0.0,0.079947,0.0,NaN,0.0,0.011677,0.078663,0.071418,0.063899,0,1,56,284,58,170,0,2,34,176,159,119,0,0,0,0,0,0,1,0,5,41,65,30,2.095489,1.0,1.255411,1.733871,1.555556,1.042683,3.627821,1.860168,2.888673,3.242113,3.339107,2.171329,3.671663,14.702458,3.17292,3.231573,1.548081,3.773979,0.988059,0.126521,0.910415,1.003262,2.156933,0.575342,NaN,NaN,24.601652,68.841414,11.437114,10.787206

Exported organelle morphology summary statistics (after unstacking) to C:\Users\redre\Documents\CohenLab\scohen_lab_repo\infer-subc\sample_data\example_quant\quant/all_datasets_2_organelle_morphology_summarystats.csv

#### **`DEFINE` - The batch_org_morph_summary_stats() function**

In [ ]:
def _batch_org_morph_summary_stats(csv_path_list: List[str],
                                   out_path: str,
                                   out_prefix: str,
                                   organelle_names: List[str]):
    """" 
    csv_path_list: List[str],
        A list of path strings where .csv files to analyze are located.
    out_path: str,
        A path string where the summary data file will be output to
    out_prefix: str
        The prefix used to name the output file. An "_" will be included between this prefix and the file suffix.
    organelle_names: List[str],
        A list of organelle names used in the organelle morphology quantification (batch_process_org_morph function)
    """
    # for keeping track of dataset and file numbers
    ds_count = 0
    fl_count = 0

    ###################
    # Read in the csv files and combine them into one of each type
    ###################
    # create empty list to hold the morphology tables from different experiments
    org_tabs = []

    # loop through all of the locations listed above and find the _org_morph files; append them to the list above
    for loc in csv_path_list:
        # list all csv files in the location
        files_store = sorted(loc.glob("*.csv"))

        # find the unique datasets in this location based on the prefixes before "_org_morphology_metrics"
        prefixes = set(f.name.split("_org_morphology_metrics")[0] for f in files_store if "_org_morphology_metrics" in f.name)
        for prefix in prefixes:
            ds_count += 1
            # select only the files from this dataset
            files_subset = [f for f in files_store if f.name.startswith(prefix +"_org_morphology_metrics")]
            for file in files_subset:
                fl_count += 1
                stem = file.stem
                if "_org_morph" in stem:
                    test_orgs = pd.read_csv(file, index_col=0)
                    org_tabs.append(test_orgs)

    # combine the org_morph lists found above into one table
    org_df = pd.concat(org_tabs,axis=0, join='outer').reset_index()

    print(f"Found {fl_count} files from {ds_count} dataset(s) across {len(csv_path_list)} location(s).")


    ###################
    # summary stat group
    ###################
    group_by = ['dataset', 'image_name', 'mask_name', 'scale', 'object']
    sharedcolumns = ["SA_to_volume_ratio", "equivalent_diameter", "extent", "euler_number", "solidity", "axis_major_length"]
    
    # check if skeletonization metrics are included in the data by looking for any column names that start with "skel_"
    include_skel = any(col.startswith('skel_') for col in org_df.columns)

    # add skeleton metrics to the shared columns if they are included in the data
    if include_skel:
        skel_cols = ["skel_total_length",
                    "skel_abs_punc_count",
                    "skel_ep_count",
                    "skel_jn_count",
                    "skel_node_count",
                    "skel_brh_count"]
        skel_cols_2 = ["skel_brh_type_0_tot",
                       "skel_brh_type_1_tot",
                       "skel_brh_type_2_tot",
                       "skel_brh_type_3_tot",
                       "skel_comp_count",
                       "skel_ave_jn_deg",
                       "skel_max_deg",
                       "skel_mean_brh_str",
                       "skel_width"]
    ag_func_standard = ['mean', 'median', 'std']

    ###################
    # summarize shared measurements between org_df and contacts_df
    ###################
    tab1 = org_df[group_by + ['label']].groupby(group_by).agg(['count'])
    tab1.rename(columns={'label': 'org'}, inplace=True)
    tab2 = org_df[group_by + ['volume', 'surface_area']].groupby(group_by).agg(['sum'] + ag_func_standard)
    tab3 = org_df[group_by + sharedcolumns].groupby(group_by).agg(ag_func_standard)
    org_summary = pd.merge(tab1, tab2, 'outer', on=group_by)
    org_summary = pd.merge(org_summary, tab3, 'outer', on=group_by)
    if include_skel:
        tab4 = org_df[group_by + skel_cols].groupby(group_by).agg(['sum'] + ag_func_standard)
        tab5 = org_df[group_by + skel_cols_2].groupby(group_by).agg(ag_func_standard)
        org_summary = pd.merge(org_summary, tab4, 'outer', on=group_by)
        org_summary = pd.merge(org_summary, tab5, 'outer', on=group_by)

    # Get mask_name and corresponding volume column per group & calculate volume fraction
    mask_names = org_df.groupby(group_by)['mask_name'].first()
    mask_volume_data = org_df.groupby(group_by).first().apply(lambda row: row[f"{mask_names.loc[row.name]}_volume"], axis=1)
    org_summary.insert(org_summary.columns.get_loc(('volume', 'sum')) + 1, ('volume', 'fraction'), org_summary[('volume', 'sum')]/mask_volume_data)

    ###################
    # additional skeleton summarization inspired by mitograph measurments (if skeletonization is included)
    ###################


    if include_skel:
        # a temporary table used to calculate the average node degree, fusion score, fission score, connectivity, and heterogeneity for each organelle per cell
        # these measurements are inspired by the mitograph quantification metrics, but adapted to be more generalizable to different organelles
        skel_ff = org_df.assign(sum_jnxdeg = lambda x: x['skel_ave_jn_deg'] * x['skel_jn_count'],
                                is_punc = lambda df: (df['skel_type'] == "Punctate").astype(int),
                                is_rod = lambda df: (df['skel_type'] == "Rod").astype(int),
                                is_iso_cycle = lambda df: (df['skel_type'] == "Isolated Cycle").astype(int),
                                is_network = lambda df: (df['skel_type'] == "Network").astype(int)).groupby(group_by).agg({
            'label': 'count',
            'volume': ['mean','std'],
            'skel_total_length': ['max','sum','mean','std'],
            'skel_brh_count': ['sum','mean','std'],
            'skel_abs_punc_count': ['sum'],
            'skel_ep_count': 'sum',
            'skel_jn_count': ['sum'],
            'skel_node_count': ['sum','mean','std'],
            'sum_jnxdeg': 'sum',
            'skel_width': ['mean','std'],
            'is_punc': 'sum',
            'is_rod': 'sum',
            'is_iso_cycle': 'sum',
            'is_network': 'sum'
        }).assign(
            punctate_count = lambda df: df['is_punc'],
            rod_count = lambda df: df['is_rod'],
            iso_cycle_count = lambda df: df['is_iso_cycle'],
            network_count = lambda df: df['is_network'],
            skel_avg_node_deg = lambda df: (df['sum_jnxdeg','sum'] + df['skel_ep_count','sum']) / df['skel_node_count','sum'],
            skel_fusion_score = lambda df: (df['skel_total_length','max']/df['skel_total_length','sum']) + 
                (df['skel_total_length','sum']/df['skel_brh_count','sum']) + df['skel_avg_node_deg'],
            skel_fission_score = lambda df: (df['label','count']/df['skel_total_length','sum']) + 
                (df['skel_node_count','sum']/df['skel_total_length','sum']) + (df['skel_brh_count','sum']/df['skel_total_length','sum']),
            skel_connectivity = lambda df: df['skel_fusion_score']/df['skel_fission_score'],
            skel_heterogeneity = lambda df: (df['skel_node_count','std']/df['skel_node_count','mean']) + 
                (df['skel_brh_count','std']/df['skel_brh_count','mean']) +
                (df['skel_total_length','std']/df['skel_total_length','mean']) +
                (df['volume','std']/df['volume','mean']) +
                (df['skel_width','std']/df['skel_width','mean']) +
                df['skel_avg_node_deg']
        )

        # columns from the fusion/fission table to add to the morphology summary table
        skel_sum_metrics = ["punctate_count", "rod_count", "iso_cycle_count", "network_count",
            "skel_avg_node_deg", "skel_fusion_score", "skel_fission_score", "skel_connectivity", "skel_heterogeneity"]

        # merge these additional metrics back into the org_summary table
        org_summary = pd.merge(org_summary, skel_ff[skel_sum_metrics], on=group_by, how='outer')

    ###################
    # fill gaps & NA values
    ###################
    # Ensure all possible interactions are represented (if missing fill with NaN)
    for ind in org_summary.index.droplevel(4).unique().to_list():
        for row in organelle_names:
            if ind+(row,) not in org_summary.index:
                org_summary.loc[ind+(row,)] = np.nan

    # fill NA with 0 for specific columns
    fill_dict = {('org', 'count'): 0, 
                ('volume', 'sum'): 0,
                ('surface_area', 'sum'): 0,
                ('volume', 'fraction'): 0}
    org_summary = org_summary.fillna(value=fill_dict)

    # if (org, count) is 1, set mean, median, and std to NaN
    single_site_mask = org_summary[('org', 'count')] == 1
    for col in sharedcolumns+['volume', 'surface_area']:
        org_summary.loc[single_site_mask, (col, 'std')] = np.nan

    org_summary.sort_index(inplace=True)

    ###################
    # flatten datasheet and export
    ###################
    # export before unstacking
    if (Path(out_path) / f"{out_prefix}_per_org_morphology_summarystats.csv").exists():
        raise FileExistsError(f"CAUTION: {out_prefix}_per_org_morphology_summarystats.csv already exists and will not be overwritten. Move the existing file, change the `out_prefix` or `quant_data_path` to continue without error.")
    else:
        org_summary.to_csv(str(out_path) + f"/{out_prefix}_per_org_morphology_summarystats.csv", mode='x')
        print(f"Exported per-organelle morphology summary statistics (before unstacking) to {quant_data_path}/{out_prefix}_per_org_morphology_summarystats.csv")

    org_morph_final = org_summary.unstack(-1)
    org_morph_final.columns = ["_".join((col_name[1], col_name[-1], col_name[0])) for col_name in org_morph_final.columns.to_flat_index()]
    org_morph_final.columns = [col.replace('sum', 'total') for col in org_morph_final.columns]
    org_morph_final.columns = [col.replace(col, 'mask_volume') if 'mask' in col else col for col in org_morph_final.columns]
    org_morph_final = org_morph_final.loc[:, ~org_morph_final.columns.duplicated()]
    org_morph_final.reset_index(inplace=True)

    ###################
    # export summary sheets
    ###################
    if (Path(out_path) / f"{out_prefix}_organelle_morphology_summarystats.csv").exists():
        raise FileExistsError(f"CAUTION: {out_prefix}_organelle_morphology_summarystats.csv already exists and will not be overwritten. Move the existing file, change the `out_prefix` or `quant_data_path` to continue without error.")
    else:
        org_morph_final.to_csv(str(out_path) + f"/{out_prefix}_organelle_morphology_summarystats.csv", mode='x')
        print(f"Exported organelle morphology summary statistics (after unstacking) to {out_path}/{out_prefix}_organelle_morphology_summarystats.csv")
    print(f"Organelle morphology summary is complete.")
    return org_summary

#### &#x1F3C3; **Run code; no user input required**

&#x1F453; **FYI:** This code block applies the function above to your test image. The settings specified above are applied here.

In [ ]:
# define new out_prefix for comparison
out_prefix2 = "all_datasets_1-comparison"

# test the function above
test_org_summary = _batch_org_morph_summary_stats(csv_path_list = csv_path_list,
                                                  out_path = quant_data_path,
                                                  out_prefix = out_prefix2,
                                                  organelle_names = org_file_names)

# compare the output files from both dataset runs to ensure they are identical
morpho_file1 = quant_data_path / f"{out_prefix}_organelle_morphology_summarystats.csv"
morpho_file2 = quant_data_path / f"{out_prefix2}_organelle_morphology_summarystats.csv"

# determine if files are identical except for the dataset name column
if morpho_file1.exists() and morpho_file2.exists():
    morpho_1 = pd.read_csv(morpho_file1)
    morpho_2 = pd.read_csv(morpho_file2)
    print("\nMorphology summarystats files identical:", morpho_1.equals(morpho_2))

Found 3 files from 3 dataset(s) across 1 location(s).
Exported per-organelle morphology summary statistics (before unstacking) to C:\Users\redre\Documents\CohenLab\scohen_lab_repo\infer-subc\sample_data\example_quant\quant/all_datasets_2-comparison_per_org_morphology_summarystats.csv
Exported organelle morphology summary statistics (after unstacking) to C:\Users\redre\Documents\CohenLab\scohen_lab_repo\infer-subc\sample_data\example_quant\quant/all_datasets_2-comparison_organelle_morphology_summarystats.csv
Organelle morphology summary is complete.

Morphology summarystats files identical: True

##### &#x1F453; **FYI:** This function has been added to `infer_subc.quantification.morphology` and can be imported with the following:
> ```python
> from infer_subc.quantification.morphology import batch_org_morph_summary_stats
> ```

In [36]:
from infer_subc.quantification.morphology import batch_org_morph_summary_stats

# define new out_prefix for comparison
out_prefix3 = "all_datasets_1-FINAL"

# test the function above
test_org_summary = _batch_org_morph_summary_stats(csv_path_list = csv_path_list,
                                                  out_path = quant_data_path,
                                                  out_prefix = out_prefix3,
                                                  organelle_names = org_file_names)

# compare the output files from both dataset runs to ensure they are identical
morpho_file3 = quant_data_path / f"{out_prefix3}_organelle_morphology_summarystats.csv"
morpho_file2 = quant_data_path / f"{out_prefix2}_organelle_morphology_summarystats.csv"

# determine if files are identical except for the dataset name column
if morpho_file3.exists() and morpho_file2.exists():
    morph_3 = pd.read_csv(morpho_file3)
    morph_2 = pd.read_csv(morpho_file2)
    print("\nMorphology summarystats files identical:", morph_3.equals(morph_2))

Found 3 files from 3 dataset(s) across 1 location(s).
Exported per-organelle morphology summary statistics (before unstacking) to C:\Users\redre\Documents\CohenLab\scohen_lab_repo\infer-subc\sample_data\example_quant\quant/all_datasets_1-FINAL_per_org_morphology_summarystats.csv
Exported organelle morphology summary statistics (after unstacking) to C:\Users\redre\Documents\CohenLab\scohen_lab_repo\infer-subc\sample_data\example_quant\quant/all_datasets_1-FINAL_organelle_morphology_summarystats.csv
Organelle morphology summary is complete.

Morphology summarystats files identical: True

-----
-----

## **EXECUTE QUANTIFICATION** <a id='execute'></a>

### **`STEP 1` - 🧪 Batch process *multiple cells* from a <ins>SINGLE EXPERIMENT</ins>**

#### &#x1F6D1; &#x270D; **User Input Required:**

Please specify the following information about your data: 
- `out_file_name`: The prefix to use when naming the output datatable. Do not add a separator; "_" will be added between your prefix and the base name given in the function below.
- `seg_path`: Path or str to the folder that contains the segmentation tiff files
- `out_path`: Path or str to the folder that the output datatables will be saved to
- `raw_path`: Path or str to the folder that contains the raw image files
- `raw_file_type`: The file type of the raw data; ex - ".tiff", ".czi"
- `organelle_names`: A list of all organelle names that will be analyzed; the names should be the same as the suffix used to name each of the tiff segmentation files. Note: the intensity measurements collect per region (from get_region_morphology_3D function) will only be from channels associated to these organelles 
- `organelle_channels`: A list of channel indices associated to respective organelle staining in the raw image; the indices should listed in same order in which the respective segmentation name is listed in organelle_names
- `region_names`: A list of regions, or masks, to measure; the order should correlate to the order of the channels in the "masks" output segmentation file
- `mask`: The name of the region to use as the mask when measuring the organelles; this should be one of the names listed in regions list; usually this will be the "cell" mask
- `scale`: A tuple that contains the real world dimensions for each dimension in the image (Z, Y, X)
- `seg_suffix`: Any additional text that is included in the segmentation tiff files between the file stem and the segmentation suffix, not including the initial "-"

The defaults below utilize the user input from the `IMPORTS` section.

In [37]:
out_file_name = "20241204_test"
seg_path = seg_data_path
out_path = quant_data_path
raw_path = raw_data_path
raw_file_type = raw_img_type
channel_axis = channel_axis
organelle_names = org_file_names
organelle_channels = org_channels_ordered
region_names = regions_file_names
mask_name = mask_name
scale = True
include_skel = include_skel
seg_suffix = suffix_separator

#### &#x1F3C3; **Run code; no user input required**
&#x1F453; **FYI:** This code block uses the inputs provided above to run the batch processing. The table that is saved to you files is also printed below for easy access.

In [39]:
batch_org_morph_table = batch_process_org_morph(out_file_name,
                                                raw_path,
                                                seg_path,
                                                out_path, 
                                                raw_file_type,
                                                channel_axis,
                                                organelle_names,
                                                organelle_channels,
                                                region_names,
                                                mask_name,
                                                scale,
                                                include_skel,
                                                seg_suffix)

batch_org_morph_table

Quantifying organelle morphology from 05052022_astro_control_2_Linear unmixing_0_cmle.ome.tiff
Warning(s) suppressed while quantifying lyso. See 'method_morphology.ipynb' notebook for more details.
Warning(s) suppressed while quantifying mito. See 'method_morphology.ipynb' notebook for more details.
Warning(s) suppressed while quantifying golgi. See 'method_morphology.ipynb' notebook for more details.
Warning(s) suppressed while quantifying perox. See 'method_morphology.ipynb' notebook for more details.
Warning(s) suppressed while quantifying ER. See 'method_morphology.ipynb' notebook for more details.
Warning(s) suppressed while quantifying LD. See 'method_morphology.ipynb' notebook for more details.
Completed quantification of C:\Users\redre\Documents\CohenLab\scohen_lab_repo\infer-subc\sample_data\example_quant\raw\05052022_astro_control_2_Linear unmixing_0_cmle.ome.tiff in 5.719041971365611 mins.
1/1 images have been processed.
Time elapsed: 5.719041971365611 mins
Quantification for 1 files is COMPLETE! Files saved to 'C:\Users\redre\Documents\CohenLab\scohen_lab_repo\infer-subc\sample_data\example_quant\quant'.
It took 5.719070521990458 minutes to quantify these files.

### **`STEP 2` - 🧮 Summarize metrics *per cell* across <INS>ONE OR MORE EXPERIMENTS</ins>**

#### &#x1F6D1; &#x270D; **User Input Required:**

Please specify the following information about your data: 
- `csv_path_list`: A list of path strings where .csv files to analyze are located.
- `out_path`: A path string where the summary data file will be output to
- `out_preffix`: The prefix used to name the output file. An "_" will be included between this prefix and the file suffix.

In [40]:
csv_path_list = csv_path_list
out_path = quant_data_path
out_prefix = out_prefix
organelle_names = org_file_names

#### &#x1F3C3; **Run code; no user input required**
&#x1F453; **FYI:** This code block uses the inputs provided above to run the batch processing. The table that is saved to you files is also printed below for easy access.

In [42]:
test_org_summary = batch_org_morph_summary_stats(csv_path_list = csv_path_list,
                                                  out_path = out_path,
                                                  out_prefix = out_prefix,
                                                  organelle_names = organelle_names)

test_org_summary

Found 4 files from 4 dataset(s) across 1 location(s).
Exported per-organelle morphology summary statistics (before unstacking) to C:\Users\redre\Documents\CohenLab\scohen_lab_repo\infer-subc\sample_data\example_quant\quant/all_datasets_2_per_org_morphology_summarystats.csv
Exported organelle morphology summary statistics (after unstacking) to C:\Users\redre\Documents\CohenLab\scohen_lab_repo\infer-subc\sample_data\example_quant\quant/all_datasets_2_organelle_morphology_summarystats.csv
Organelle morphology summary is complete.

                                                                                                                              org  \
                                                                                                                            count
dataset                       image_name                                          mask_name scale                    object
20241204_test                 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER         1
                                                                                                                     LD         3
                                                                                                                     golgi     95
                                                                                                                     lyso     501
                                                                                                                     mito     282
                                                                                                                     perox    319
test_dataset_1                05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER         1
                                                                                                                     LD         3
                                                                                                                     golgi     95
                                                                                                                     lyso     501
                                                                                                                     mito     282
                                                                                                                     perox    319
test_dataset_1-comparison     05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER         1
                                                                                                                     LD         3
                                                                                                                     golgi     95
                                                                                                                     lyso     501
                                                                                                                     mito     282
                                                                                                                     perox    319
test_dataset_1-testcomparison 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER         1
                                                                                                                     LD         3
                                                                                                                     golgi     95
                                                                                                                     lyso     501
                                                                                                                     mito     282
                                                                                                                     perox    319

                                                                                                                                  volume  \
                                                                                                                                     sum
dataset                       image_name                                          mask_name scale                    object
20241204_test                 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      1633.166259
                                                                                                                     LD         0.455692
                                                                                                                     golgi     52.786906
                                                                                                                     lyso     725.500337
                                                                                                                     mito     200.000880
                                                                                                                     perox    114.933228
test_dataset_1                05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      1633.166259
                                                                                                                     LD         0.455692
                                                                                                                     golgi     52.786906
                                                                                                                     lyso     725.500337
                                                                                                                     mito     200.000880
                                                                                                                     perox    114.933228
test_dataset_1-comparison     05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      1633.166259
                                                                                                                     LD         0.455692
                                                                                                                     golgi     52.786906
                                                                                                                     lyso     725.500337
                                                                                                                     mito     200.000880
                                                                                                                     perox    114.933228
test_dataset_1-testcomparison 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      1633.166259
                                                                                                                     LD         0.455692
                                                                                                                     golgi     52.786906
                                                                                                                     lyso     725.500337
                                                                                                                     mito     200.000880
                                                                                                                     perox    114.933228

                                                                                                                                       \
                                                                                                                             fraction
dataset                       image_name                                          mask_name scale                    object
20241204_test                 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      0.409385
                                                                                                                     LD      0.000114
                                                                                                                     golgi   0.013232
                                                                                                                     lyso    0.181861
                                                                                                                     mito    0.050134
                                                                                                                     perox   0.028810
test_dataset_1                05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      0.409385
                                                                                                                     LD      0.000114
                                                                                                                     golgi   0.013232
                                                                                                                     lyso    0.181861
                                                                                                                     mito    0.050134
                                                                                                                     perox   0.028810
test_dataset_1-comparison     05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      0.409385
                                                                                                                     LD      0.000114
                                                                                                                     golgi   0.013232
                                                                                                                     lyso    0.181861
                                                                                                                     mito    0.050134
                                                                                                                     perox   0.028810
test_dataset_1-testcomparison 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      0.409385
                                                                                                                     LD      0.000114
                                                                                                                     golgi   0.013232
                                                                                                                     lyso    0.181861
                                                                                                                     mito    0.050134
                                                                                                                     perox   0.028810

                                                                                                                                          \
                                                                                                                                    mean
dataset                       image_name                                          mask_name scale                    object
20241204_test                 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      1633.166259
                                                                                                                     LD         0.151897
                                                                                                                     golgi      0.555652
                                                                                                                     lyso       1.448104
                                                                                                                     mito       0.709223
                                                                                                                     perox      0.360292
test_dataset_1                05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      1633.166259
                                                                                                                     LD         0.151897
                                                                                                                     golgi      0.555652
                                                                                                                     lyso       1.448104
                                                                                                                     mito       0.709223
                                                                                                                     perox      0.360292
test_dataset_1-comparison     05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      1633.166259
                                                                                                                     LD         0.151897
                                                                                                                     golgi      0.555652
                                                                                                                     lyso       1.448104
                                                                                                                     mito       0.709223
                                                                                                                     perox      0.360292
test_dataset_1-testcomparison 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      1633.166259
                                                                                                                     LD         0.151897
                                                                                                                     golgi      0.555652
                                                                                                                     lyso       1.448104
                                                                                                                     mito       0.709223
                                                                                                                     perox      0.360292

                                                                                                                                          \
                                                                                                                                  median
dataset                       image_name                                          mask_name scale                    object
20241204_test                 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      1633.166259
                                                                                                                     LD         0.083544
                                                                                                                     golgi      0.058227
                                                                                                                     lyso       0.098733
                                                                                                                     mito       0.254428
                                                                                                                     perox      0.177214
test_dataset_1                05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      1633.166259
                                                                                                                     LD         0.083544
                                                                                                                     golgi      0.058227
                                                                                                                     lyso       0.098733
                                                                                                                     mito       0.254428
                                                                                                                     perox      0.177214
test_dataset_1-comparison     05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      1633.166259
                                                                                                                     LD         0.083544
                                                                                                                     golgi      0.058227
                                                                                                                     lyso       0.098733
                                                                                                                     mito       0.254428
                                                                                                                     perox      0.177214
test_dataset_1-testcomparison 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER      1633.166259
                                                                                                                     LD         0.083544
                                                                                                                     golgi      0.058227
                                                                                                                     lyso       0.098733
                                                                                                                     mito       0.254428
                                                                                                                     perox      0.177214

                                                                                                                                        \
                                                                                                                                   std
dataset                       image_name                                          mask_name scale                    object
20241204_test                 05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER            NaN
                                                                                                                     LD       0.152466
                                                                                                                     golgi    3.352017
                                                                                                                     lyso    25.649103
                                                                                                                     mito     1.468134
                                                                                                                     perox    0.731846
test_dataset_1                05052022_astro_control_2_Linear unmixing_0_cmle.ome cell      (0.3961, 0.0799, 0.0799) ER            NaN
                                                                                                                     LD       0.152466
                                                                                                                     golgi    3.352017
                                                                                                                     lyso    25.649103

-----
-----
# 🎉 **CONGRATULATIONS!!**
### **You've successfully quantified organelle morphology using the modular `2.1._organelle_morphology` notebook.**

Continue on to other quantification notebooks as needed:
- [2.2 Organelle interactions]() (amounts, size, shape)
- [2.3 Subcellular distribution]() in XY and Z separately (of organelles and interaction sites)
- [2.4 Cell morphology]() (size, shape)